// Code generated by smithy-go-codegen DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/schemas"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This test serializes strings, numbers, and boolean values.
func (c *Client) SimpleInputParams(ctx context.Context, params *SimpleInputParamsInput, optFns ...func(*Options)) (*SimpleInputParamsOutput, error) {
	if params == nil {
		params = &SimpleInputParamsInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "SimpleInputParams", params, optFns, c.addOperationSimpleInputParamsMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*SimpleInputParamsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type SimpleInputParamsInput struct {
	Bam *int32

	Bar *string

	Baz *bool

	Boo *float64

	FloatValue *float32

	Foo *string

	FooEnum types.FooEnum

	IntegerEnum types.IntegerEnum

	Qux []byte

	noSmithyDocumentSerde
}

func (v *SimpleInputParamsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleInputParamsInput)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Bam, v.Bam)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Bar, v.Bar)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Baz, v.Baz)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Boo, v.Boo)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_FloatValue, v.FloatValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Foo, v.Foo)
	s.WriteString(schemas.SmithyGoSynthetic_SimpleInputParamsInput_FooEnum, string(v.FooEnum))
	s.WriteInt32(schemas.SmithyGoSynthetic_SimpleInputParamsInput_IntegerEnum, int32(v.IntegerEnum))
	s.WriteBlob(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Qux, v.Qux)
	s.CloseMap()
}
func (v *SimpleInputParamsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleInputParamsInput, func(s *smithy.Schema) error {
		switch s {
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_Bam:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Bam, &v.Bam)
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_Bar:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Bar, &v.Bar)
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_Baz:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Baz, &v.Baz)
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_Boo:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Boo, &v.Boo)
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_FloatValue:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_FloatValue, &v.FloatValue)
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_Foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Foo, &v.Foo)
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_FooEnum:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_SimpleInputParamsInput_FooEnum, &ev); err != nil {
				return err
			}
			v.FooEnum = types.FooEnum(ev)
			return nil
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_IntegerEnum:
			var ev int32
			if err := d.ReadInt32(schemas.SmithyGoSynthetic_SimpleInputParamsInput_IntegerEnum, &ev); err != nil {
				return err
			}
			v.IntegerEnum = types.IntegerEnum(ev)
			return nil
		case schemas.SmithyGoSynthetic_SimpleInputParamsInput_Qux:
			return d.ReadBlob(schemas.SmithyGoSynthetic_SimpleInputParamsInput_Qux, &v.Qux)
		}
		return nil
	})
}

type SimpleInputParamsOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *SimpleInputParamsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleInputParamsOutput)
	s.CloseMap()
}
func (v *SimpleInputParamsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleInputParamsOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationSimpleInputParamsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleInputParams, schemas.SmithyGoSynthetic_SimpleInputParamsInput, schemas.SmithyGoSynthetic_SimpleInputParamsOutput)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleInputParams, schemas.SmithyGoSynthetic_SimpleInputParamsInput, schemas.SmithyGoSynthetic_SimpleInputParamsOutput), output: &SimpleInputParamsOutput{}}, middleware.After); err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "SimpleInputParams"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opSimpleInputParams(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opSimpleInputParams(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "SimpleInputParams",
	}
}
