// Code generated by smithy-go-codegen DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/schemas"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This test serializes simple and complex maps.
func (c *Client) QueryMaps(ctx context.Context, params *QueryMapsInput, optFns ...func(*Options)) (*QueryMapsOutput, error) {
	if params == nil {
		params = &QueryMapsInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "QueryMaps", params, optFns, c.addOperationQueryMapsMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*QueryMapsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type QueryMapsInput struct {
	ComplexMapArg map[string]types.GreetingStruct

	FlattenedMap map[string]string

	FlattenedMapWithXmlName map[string]string

	MapArg map[string]string

	MapOfLists map[string][]string

	MapWithXmlMemberName map[string]string

	NestedStructWithMap *types.NestedStructWithMap

	RenamedMapArg map[string]string

	noSmithyDocumentSerde
}

func (v *QueryMapsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_QueryMapsInput)
	serializeComplexMap(s, schemas.SmithyGoSynthetic_QueryMapsInput_ComplexMapArg, v.ComplexMapArg)
	serializeStringMap(s, schemas.SmithyGoSynthetic_QueryMapsInput_FlattenedMap, v.FlattenedMap)
	serializeMapWithXmlName(s, schemas.SmithyGoSynthetic_QueryMapsInput_FlattenedMapWithXmlName, v.FlattenedMapWithXmlName)
	serializeStringMap(s, schemas.SmithyGoSynthetic_QueryMapsInput_MapArg, v.MapArg)
	serializeMapOfLists(s, schemas.SmithyGoSynthetic_QueryMapsInput_MapOfLists, v.MapOfLists)
	serializeMapWithXmlName(s, schemas.SmithyGoSynthetic_QueryMapsInput_MapWithXmlMemberName, v.MapWithXmlMemberName)
	if v.NestedStructWithMap != nil {
		s.WriteStruct(schemas.SmithyGoSynthetic_QueryMapsInput_NestedStructWithMap, v.NestedStructWithMap)
	}
	serializeStringMap(s, schemas.SmithyGoSynthetic_QueryMapsInput_RenamedMapArg, v.RenamedMapArg)
	s.CloseMap()
}
func (v *QueryMapsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_QueryMapsInput, func(s *smithy.Schema) error {
		switch s {
		case schemas.SmithyGoSynthetic_QueryMapsInput_ComplexMapArg:
			return deserializeComplexMap(d, schemas.SmithyGoSynthetic_QueryMapsInput_ComplexMapArg, &v.ComplexMapArg)
		case schemas.SmithyGoSynthetic_QueryMapsInput_FlattenedMap:
			return deserializeStringMap(d, schemas.SmithyGoSynthetic_QueryMapsInput_FlattenedMap, &v.FlattenedMap)
		case schemas.SmithyGoSynthetic_QueryMapsInput_FlattenedMapWithXmlName:
			return deserializeMapWithXmlName(d, schemas.SmithyGoSynthetic_QueryMapsInput_FlattenedMapWithXmlName, &v.FlattenedMapWithXmlName)
		case schemas.SmithyGoSynthetic_QueryMapsInput_MapArg:
			return deserializeStringMap(d, schemas.SmithyGoSynthetic_QueryMapsInput_MapArg, &v.MapArg)
		case schemas.SmithyGoSynthetic_QueryMapsInput_MapOfLists:
			return deserializeMapOfLists(d, schemas.SmithyGoSynthetic_QueryMapsInput_MapOfLists, &v.MapOfLists)
		case schemas.SmithyGoSynthetic_QueryMapsInput_MapWithXmlMemberName:
			return deserializeMapWithXmlName(d, schemas.SmithyGoSynthetic_QueryMapsInput_MapWithXmlMemberName, &v.MapWithXmlMemberName)
		case schemas.SmithyGoSynthetic_QueryMapsInput_NestedStructWithMap:
			v.NestedStructWithMap = &types.NestedStructWithMap{}
			return v.NestedStructWithMap.Deserialize(d)
		case schemas.SmithyGoSynthetic_QueryMapsInput_RenamedMapArg:
			return deserializeStringMap(d, schemas.SmithyGoSynthetic_QueryMapsInput_RenamedMapArg, &v.RenamedMapArg)
		}
		return nil
	})
}

type QueryMapsOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *QueryMapsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_QueryMapsOutput)
	s.CloseMap()
}
func (v *QueryMapsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_QueryMapsOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationQueryMapsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.QueryMaps, schemas.SmithyGoSynthetic_QueryMapsInput, schemas.SmithyGoSynthetic_QueryMapsOutput)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.QueryMaps, schemas.SmithyGoSynthetic_QueryMapsInput, schemas.SmithyGoSynthetic_QueryMapsOutput), output: &QueryMapsOutput{}}, middleware.After); err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "QueryMaps"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opQueryMaps(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opQueryMaps(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "QueryMaps",
	}
}
