// Code generated by smithy-go-codegen DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/schemas"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) XmlMapsXmlName(ctx context.Context, params *XmlMapsXmlNameInput, optFns ...func(*Options)) (*XmlMapsXmlNameOutput, error) {
	if params == nil {
		params = &XmlMapsXmlNameInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "XmlMapsXmlName", params, optFns, c.addOperationXmlMapsXmlNameMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*XmlMapsXmlNameOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type XmlMapsXmlNameInput struct {
	noSmithyDocumentSerde
}

func (v *XmlMapsXmlNameInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_XmlMapsXmlNameInput)
	s.CloseMap()
}
func (v *XmlMapsXmlNameInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_XmlMapsXmlNameInput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}

type XmlMapsXmlNameOutput struct {
	MyMap map[string]types.GreetingStruct

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *XmlMapsXmlNameOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput)
	serializeXmlMapsXmlNameOutputMap(s, schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput_myMap, v.MyMap)
	s.CloseMap()
}
func (v *XmlMapsXmlNameOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput, func(s *smithy.Schema) error {
		switch s {
		case schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput_myMap:
			return deserializeXmlMapsXmlNameOutputMap(d, schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput_myMap, &v.MyMap)
		}
		return nil
	})
}
func (c *Client) addOperationXmlMapsXmlNameMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.XmlMapsXmlName, schemas.SmithyGoSynthetic_XmlMapsXmlNameInput, schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.XmlMapsXmlName, schemas.SmithyGoSynthetic_XmlMapsXmlNameInput, schemas.SmithyGoSynthetic_XmlMapsXmlNameOutput), output: &XmlMapsXmlNameOutput{}}, middleware.After); err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "XmlMapsXmlName"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opXmlMapsXmlName(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opXmlMapsXmlName(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "XmlMapsXmlName",
	}
}
