// Code generated by smithy-go-codegen DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/schemas"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) SimpleScalarXmlProperties(ctx context.Context, params *SimpleScalarXmlPropertiesInput, optFns ...func(*Options)) (*SimpleScalarXmlPropertiesOutput, error) {
	if params == nil {
		params = &SimpleScalarXmlPropertiesInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "SimpleScalarXmlProperties", params, optFns, c.addOperationSimpleScalarXmlPropertiesMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*SimpleScalarXmlPropertiesOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type SimpleScalarXmlPropertiesInput struct {
	noSmithyDocumentSerde
}

func (v *SimpleScalarXmlPropertiesInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesInput)
	s.CloseMap()
}
func (v *SimpleScalarXmlPropertiesInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesInput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}

type SimpleScalarXmlPropertiesOutput struct {
	ByteValue *int8

	DoubleValue *float64

	EmptyStringValue *string

	FalseBooleanValue *bool

	FloatValue *float32

	IntegerValue *int32

	LongValue *int64

	ShortValue *int16

	StringValue *string

	TrueBooleanValue *bool

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *SimpleScalarXmlPropertiesOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_byteValue, v.ByteValue)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_doubleValue, v.DoubleValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_emptyStringValue, v.EmptyStringValue)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_falseBooleanValue, v.FalseBooleanValue)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_floatValue, v.FloatValue)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_integerValue, v.IntegerValue)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_longValue, v.LongValue)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_shortValue, v.ShortValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_stringValue, v.StringValue)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_trueBooleanValue, v.TrueBooleanValue)
	s.CloseMap()
}
func (v *SimpleScalarXmlPropertiesOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput, func(s *smithy.Schema) error {
		switch s {
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_byteValue:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_byteValue, &v.ByteValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_doubleValue:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_doubleValue, &v.DoubleValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_emptyStringValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_emptyStringValue, &v.EmptyStringValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_falseBooleanValue:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_falseBooleanValue, &v.FalseBooleanValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_floatValue:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_floatValue, &v.FloatValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_integerValue:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_integerValue, &v.IntegerValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_longValue:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_longValue, &v.LongValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_shortValue:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_shortValue, &v.ShortValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_stringValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_stringValue, &v.StringValue)
		case schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_trueBooleanValue:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput_trueBooleanValue, &v.TrueBooleanValue)
		}
		return nil
	})
}
func (c *Client) addOperationSimpleScalarXmlPropertiesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleScalarXmlProperties, schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesInput, schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleScalarXmlProperties, schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesInput, schemas.SmithyGoSynthetic_SimpleScalarXmlPropertiesOutput), output: &SimpleScalarXmlPropertiesOutput{}}, middleware.After); err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "SimpleScalarXmlProperties"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opSimpleScalarXmlProperties(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opSimpleScalarXmlProperties(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "SimpleScalarXmlProperties",
	}
}
