// Code generated by smithy-go-codegen DO NOT EDIT.

package query

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/schemas"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/query/types"
	smithy "github.com/aws/smithy-go"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This test serializes simple and complex lists.
func (c *Client) QueryLists(ctx context.Context, params *QueryListsInput, optFns ...func(*Options)) (*QueryListsOutput, error) {
	if params == nil {
		params = &QueryListsInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "QueryLists", params, optFns, c.addOperationQueryListsMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*QueryListsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type QueryListsInput struct {
	ComplexListArg []types.GreetingStruct

	FlattenedListArg []string

	FlattenedListArgWithXmlName []string

	ListArg []string

	ListArgWithXmlNameMember []string

	NestedWithList *types.NestedStructWithList

	noSmithyDocumentSerde
}

func (v *QueryListsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_QueryListsInput)
	serializeGreetingList(s, schemas.SmithyGoSynthetic_QueryListsInput_ComplexListArg, v.ComplexListArg)
	serializeStringList(s, schemas.SmithyGoSynthetic_QueryListsInput_FlattenedListArg, v.FlattenedListArg)
	serializeListWithXmlName(s, schemas.SmithyGoSynthetic_QueryListsInput_FlattenedListArgWithXmlName, v.FlattenedListArgWithXmlName)
	serializeStringList(s, schemas.SmithyGoSynthetic_QueryListsInput_ListArg, v.ListArg)
	serializeListWithXmlName(s, schemas.SmithyGoSynthetic_QueryListsInput_ListArgWithXmlNameMember, v.ListArgWithXmlNameMember)
	if v.NestedWithList != nil {
		s.WriteStruct(schemas.SmithyGoSynthetic_QueryListsInput_NestedWithList, v.NestedWithList)
	}
	s.CloseMap()
}
func (v *QueryListsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_QueryListsInput, func(s *smithy.Schema) error {
		switch s {
		case schemas.SmithyGoSynthetic_QueryListsInput_ComplexListArg:
			return deserializeGreetingList(d, schemas.SmithyGoSynthetic_QueryListsInput_ComplexListArg, &v.ComplexListArg)
		case schemas.SmithyGoSynthetic_QueryListsInput_FlattenedListArg:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_QueryListsInput_FlattenedListArg, &v.FlattenedListArg)
		case schemas.SmithyGoSynthetic_QueryListsInput_FlattenedListArgWithXmlName:
			return deserializeListWithXmlName(d, schemas.SmithyGoSynthetic_QueryListsInput_FlattenedListArgWithXmlName, &v.FlattenedListArgWithXmlName)
		case schemas.SmithyGoSynthetic_QueryListsInput_ListArg:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_QueryListsInput_ListArg, &v.ListArg)
		case schemas.SmithyGoSynthetic_QueryListsInput_ListArgWithXmlNameMember:
			return deserializeListWithXmlName(d, schemas.SmithyGoSynthetic_QueryListsInput_ListArgWithXmlNameMember, &v.ListArgWithXmlNameMember)
		case schemas.SmithyGoSynthetic_QueryListsInput_NestedWithList:
			v.NestedWithList = &types.NestedStructWithList{}
			return v.NestedWithList.Deserialize(d)
		}
		return nil
	})
}

type QueryListsOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (v *QueryListsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_QueryListsOutput)
	s.CloseMap()
}
func (v *QueryListsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_QueryListsOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationQueryListsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.QueryLists, schemas.SmithyGoSynthetic_QueryListsInput, schemas.SmithyGoSynthetic_QueryListsOutput)}, middleware.After); err != nil {
		return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.QueryLists, schemas.SmithyGoSynthetic_QueryListsInput, schemas.SmithyGoSynthetic_QueryListsOutput), output: &QueryListsOutput{}}, middleware.After); err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "QueryLists"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opQueryLists(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

func newServiceMetadataMiddleware_opQueryLists(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "QueryLists",
	}
}
