// Code generated by smithy-go-codegen DO NOT EDIT.


package jsonrpc

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) SimpleScalarProperties(ctx context.Context, params *SimpleScalarPropertiesInput, optFns ...func(*Options)) (*SimpleScalarPropertiesOutput, error) {
	if params == nil { params = &SimpleScalarPropertiesInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "SimpleScalarProperties", params, optFns, c.addOperationSimpleScalarPropertiesMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*SimpleScalarPropertiesOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type SimpleScalarPropertiesInput struct {
	
	DoubleValue *float64
	
	FloatValue *float32
	
	noSmithyDocumentSerde
}

func (v *SimpleScalarPropertiesInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_doubleValue, v.DoubleValue)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_floatValue, v.FloatValue)
	s.CloseMap()
}
func (v *SimpleScalarPropertiesInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_doubleValue:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_doubleValue, &v.DoubleValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_floatValue:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_floatValue, &v.FloatValue)
		}
		return nil
	})
}
type SimpleScalarPropertiesOutput struct {
	
	DoubleValue *float64
	
	FloatValue *float32
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *SimpleScalarPropertiesOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_doubleValue, v.DoubleValue)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_floatValue, v.FloatValue)
	s.CloseMap()
}
func (v *SimpleScalarPropertiesOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_doubleValue:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_doubleValue, &v.DoubleValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_floatValue:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_floatValue, &v.FloatValue)
		}
		return nil
	})
}
func (c *Client) addOperationSimpleScalarPropertiesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleScalarProperties, schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput, schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleScalarProperties, schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput, schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput), output: &SimpleScalarPropertiesOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "SimpleScalarProperties"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opSimpleScalarProperties(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opSimpleScalarProperties(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "SimpleScalarProperties",
	}
}
