// Code generated by smithy-go-codegen DO NOT EDIT.


package jsonrpc

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc/types"
)

// This example serializes enums as top level properties, in lists, sets, and maps.
func (c *Client) JsonEnums(ctx context.Context, params *JsonEnumsInput, optFns ...func(*Options)) (*JsonEnumsOutput, error) {
	if params == nil { params = &JsonEnumsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "JsonEnums", params, optFns, c.addOperationJsonEnumsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*JsonEnumsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type JsonEnumsInput struct {
	
	FooEnum1 types.FooEnum
	
	FooEnum2 types.FooEnum
	
	FooEnum3 types.FooEnum
	
	FooEnumList []types.FooEnum
	
	FooEnumMap map[string]types.FooEnum
	
	FooEnumSet []types.FooEnum
	
	noSmithyDocumentSerde
}

func (v *JsonEnumsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_JsonEnumsInput)
	s.WriteString(schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum1, string(v.FooEnum1))
	s.WriteString(schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum2, string(v.FooEnum2))
	s.WriteString(schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum3, string(v.FooEnum3))
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumList, v.FooEnumList)
	serializeFooEnumMap(s, schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumMap, v.FooEnumMap)
	serializeFooEnumSet(s, schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumSet, v.FooEnumSet)
	s.CloseMap()
}
func (v *JsonEnumsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_JsonEnumsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum1:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum1, &ev); err != nil {
			    return err
			}
			v.FooEnum1 = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum2:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum2, &ev); err != nil {
			    return err
			}
			v.FooEnum2 = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum3:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnum3, &ev); err != nil {
			    return err
			}
			v.FooEnum3 = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumList, &v.FooEnumList)
			case schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumMap:
			return deserializeFooEnumMap(d, schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumMap, &v.FooEnumMap)
			case schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumSet:
			return deserializeFooEnumSet(d, schemas.SmithyGoSynthetic_JsonEnumsInput_fooEnumSet, &v.FooEnumSet)
		}
		return nil
	})
}
type JsonEnumsOutput struct {
	
	FooEnum1 types.FooEnum
	
	FooEnum2 types.FooEnum
	
	FooEnum3 types.FooEnum
	
	FooEnumList []types.FooEnum
	
	FooEnumMap map[string]types.FooEnum
	
	FooEnumSet []types.FooEnum
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *JsonEnumsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_JsonEnumsOutput)
	s.WriteString(schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum1, string(v.FooEnum1))
	s.WriteString(schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum2, string(v.FooEnum2))
	s.WriteString(schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum3, string(v.FooEnum3))
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumList, v.FooEnumList)
	serializeFooEnumMap(s, schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumMap, v.FooEnumMap)
	serializeFooEnumSet(s, schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumSet, v.FooEnumSet)
	s.CloseMap()
}
func (v *JsonEnumsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_JsonEnumsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum1:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum1, &ev); err != nil {
			    return err
			}
			v.FooEnum1 = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum2:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum2, &ev); err != nil {
			    return err
			}
			v.FooEnum2 = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum3:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnum3, &ev); err != nil {
			    return err
			}
			v.FooEnum3 = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumList, &v.FooEnumList)
			case schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumMap:
			return deserializeFooEnumMap(d, schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumMap, &v.FooEnumMap)
			case schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumSet:
			return deserializeFooEnumSet(d, schemas.SmithyGoSynthetic_JsonEnumsOutput_fooEnumSet, &v.FooEnumSet)
		}
		return nil
	})
}
func (c *Client) addOperationJsonEnumsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.JsonEnums, schemas.SmithyGoSynthetic_JsonEnumsInput, schemas.SmithyGoSynthetic_JsonEnumsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.JsonEnums, schemas.SmithyGoSynthetic_JsonEnumsInput, schemas.SmithyGoSynthetic_JsonEnumsOutput), output: &JsonEnumsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "JsonEnums"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opJsonEnums(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opJsonEnums(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "JsonEnums",
	}
}
