// Code generated by smithy-go-codegen DO NOT EDIT.


package jsonrpc

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc/types"
)

func (c *Client) KitchenSinkOperation(ctx context.Context, params *KitchenSinkOperationInput, optFns ...func(*Options)) (*KitchenSinkOperationOutput, error) {
	if params == nil { params = &KitchenSinkOperationInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "KitchenSinkOperation", params, optFns, c.addOperationKitchenSinkOperationMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*KitchenSinkOperationOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type KitchenSinkOperationInput struct {
	
	Blob []byte
	
	Boolean *bool
	
	Double *float64
	
	EmptyStruct *types.EmptyStruct
	
	Float *float32
	
	HttpdateTimestamp *time.Time
	
	Integer *int32
	
	Iso8601Timestamp *time.Time
	
	// This value conforms to the media type: application/json
	JsonValue *string
	
	ListOfLists [][]string
	
	ListOfMapsOfStrings []map[string]string
	
	ListOfStrings []string
	
	ListOfStructs []types.SimpleStruct
	
	Long *int64
	
	MapOfListsOfStrings map[string][]string
	
	MapOfMaps map[string]map[string]string
	
	MapOfStrings map[string]string
	
	MapOfStructs map[string]types.SimpleStruct
	
	RecursiveList []types.KitchenSink
	
	RecursiveMap map[string]types.KitchenSink
	
	RecursiveStruct *types.KitchenSink
	
	SimpleStruct *types.SimpleStruct
	
	String_ *string
	
	StructWithJsonName *types.StructWithJsonName
	
	Timestamp *time.Time
	
	UnixTimestamp *time.Time
	
	noSmithyDocumentSerde
}

func (v *KitchenSinkOperationInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_KitchenSinkOperationInput)
	s.WriteBlob(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Blob, v.Blob)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Boolean, v.Boolean)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Double, v.Double)
	if (v.EmptyStruct != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_EmptyStruct, v.EmptyStruct) }
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Float, v.Float)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_HttpdateTimestamp, v.HttpdateTimestamp)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Integer, v.Integer)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Iso8601Timestamp, v.Iso8601Timestamp)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_JsonValue, v.JsonValue)
	serializeListOfListOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfLists, v.ListOfLists)
	serializeListOfMapsOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfMapsOfStrings, v.ListOfMapsOfStrings)
	serializeListOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfStrings, v.ListOfStrings)
	serializeListOfStructs(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfStructs, v.ListOfStructs)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Long, v.Long)
	serializeMapOfListsOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfListsOfStrings, v.MapOfListsOfStrings)
	serializeMapOfMapOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfMaps, v.MapOfMaps)
	serializeMapOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfStrings, v.MapOfStrings)
	serializeMapOfStructs(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfStructs, v.MapOfStructs)
	serializeListOfKitchenSinks(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveList, v.RecursiveList)
	serializeMapOfKitchenSinks(s, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveMap, v.RecursiveMap)
	if (v.RecursiveStruct != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveStruct, v.RecursiveStruct) }
	if (v.SimpleStruct != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_SimpleStruct, v.SimpleStruct) }
	s.WriteStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_String, v.String_)
	if (v.StructWithJsonName != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_StructWithJsonName, v.StructWithJsonName) }
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Timestamp, v.Timestamp)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_UnixTimestamp, v.UnixTimestamp)
	s.CloseMap()
}
func (v *KitchenSinkOperationInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Blob:
			return d.ReadBlob(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Blob, &v.Blob)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Boolean:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Boolean, &v.Boolean)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Double:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Double, &v.Double)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_EmptyStruct:
			v.EmptyStruct = &types.EmptyStruct{}
			return v.EmptyStruct.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Float:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Float, &v.Float)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_HttpdateTimestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_HttpdateTimestamp, &v.HttpdateTimestamp)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Integer:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Integer, &v.Integer)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Iso8601Timestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Iso8601Timestamp, &v.Iso8601Timestamp)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_JsonValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_JsonValue, &v.JsonValue)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfLists:
			return deserializeListOfListOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfLists, &v.ListOfLists)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfMapsOfStrings:
			return deserializeListOfMapsOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfMapsOfStrings, &v.ListOfMapsOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfStrings:
			return deserializeListOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfStrings, &v.ListOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfStructs:
			return deserializeListOfStructs(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_ListOfStructs, &v.ListOfStructs)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Long:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Long, &v.Long)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfListsOfStrings:
			return deserializeMapOfListsOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfListsOfStrings, &v.MapOfListsOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfMaps:
			return deserializeMapOfMapOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfMaps, &v.MapOfMaps)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfStrings:
			return deserializeMapOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfStrings, &v.MapOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfStructs:
			return deserializeMapOfStructs(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_MapOfStructs, &v.MapOfStructs)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveList:
			return deserializeListOfKitchenSinks(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveList, &v.RecursiveList)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveMap:
			return deserializeMapOfKitchenSinks(d, schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveMap, &v.RecursiveMap)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_RecursiveStruct:
			v.RecursiveStruct = &types.KitchenSink{}
			return v.RecursiveStruct.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_SimpleStruct:
			v.SimpleStruct = &types.SimpleStruct{}
			return v.SimpleStruct.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_String:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_String, &v.String_)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_StructWithJsonName:
			v.StructWithJsonName = &types.StructWithJsonName{}
			return v.StructWithJsonName.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Timestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_Timestamp, &v.Timestamp)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationInput_UnixTimestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationInput_UnixTimestamp, &v.UnixTimestamp)
		}
		return nil
	})
}
type KitchenSinkOperationOutput struct {
	
	Blob []byte
	
	Boolean *bool
	
	Double *float64
	
	EmptyStruct *types.EmptyStruct
	
	Float *float32
	
	HttpdateTimestamp *time.Time
	
	Integer *int32
	
	Iso8601Timestamp *time.Time
	
	// This value conforms to the media type: application/json
	JsonValue *string
	
	ListOfLists [][]string
	
	ListOfMapsOfStrings []map[string]string
	
	ListOfStrings []string
	
	ListOfStructs []types.SimpleStruct
	
	Long *int64
	
	MapOfListsOfStrings map[string][]string
	
	MapOfMaps map[string]map[string]string
	
	MapOfStrings map[string]string
	
	MapOfStructs map[string]types.SimpleStruct
	
	RecursiveList []types.KitchenSink
	
	RecursiveMap map[string]types.KitchenSink
	
	RecursiveStruct *types.KitchenSink
	
	SimpleStruct *types.SimpleStruct
	
	String_ *string
	
	StructWithJsonName *types.StructWithJsonName
	
	Timestamp *time.Time
	
	UnixTimestamp *time.Time
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *KitchenSinkOperationOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput)
	s.WriteBlob(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Blob, v.Blob)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Boolean, v.Boolean)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Double, v.Double)
	if (v.EmptyStruct != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_EmptyStruct, v.EmptyStruct) }
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Float, v.Float)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_HttpdateTimestamp, v.HttpdateTimestamp)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Integer, v.Integer)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Iso8601Timestamp, v.Iso8601Timestamp)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_JsonValue, v.JsonValue)
	serializeListOfListOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfLists, v.ListOfLists)
	serializeListOfMapsOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfMapsOfStrings, v.ListOfMapsOfStrings)
	serializeListOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfStrings, v.ListOfStrings)
	serializeListOfStructs(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfStructs, v.ListOfStructs)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Long, v.Long)
	serializeMapOfListsOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfListsOfStrings, v.MapOfListsOfStrings)
	serializeMapOfMapOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfMaps, v.MapOfMaps)
	serializeMapOfStrings(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfStrings, v.MapOfStrings)
	serializeMapOfStructs(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfStructs, v.MapOfStructs)
	serializeListOfKitchenSinks(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveList, v.RecursiveList)
	serializeMapOfKitchenSinks(s, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveMap, v.RecursiveMap)
	if (v.RecursiveStruct != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveStruct, v.RecursiveStruct) }
	if (v.SimpleStruct != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_SimpleStruct, v.SimpleStruct) }
	s.WriteStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_String, v.String_)
	if (v.StructWithJsonName != nil) { s.WriteStruct(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_StructWithJsonName, v.StructWithJsonName) }
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Timestamp, v.Timestamp)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_UnixTimestamp, v.UnixTimestamp)
	s.CloseMap()
}
func (v *KitchenSinkOperationOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Blob:
			return d.ReadBlob(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Blob, &v.Blob)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Boolean:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Boolean, &v.Boolean)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Double:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Double, &v.Double)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_EmptyStruct:
			v.EmptyStruct = &types.EmptyStruct{}
			return v.EmptyStruct.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Float:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Float, &v.Float)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_HttpdateTimestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_HttpdateTimestamp, &v.HttpdateTimestamp)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Integer:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Integer, &v.Integer)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Iso8601Timestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Iso8601Timestamp, &v.Iso8601Timestamp)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_JsonValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_JsonValue, &v.JsonValue)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfLists:
			return deserializeListOfListOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfLists, &v.ListOfLists)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfMapsOfStrings:
			return deserializeListOfMapsOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfMapsOfStrings, &v.ListOfMapsOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfStrings:
			return deserializeListOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfStrings, &v.ListOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfStructs:
			return deserializeListOfStructs(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_ListOfStructs, &v.ListOfStructs)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Long:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Long, &v.Long)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfListsOfStrings:
			return deserializeMapOfListsOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfListsOfStrings, &v.MapOfListsOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfMaps:
			return deserializeMapOfMapOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfMaps, &v.MapOfMaps)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfStrings:
			return deserializeMapOfStrings(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfStrings, &v.MapOfStrings)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfStructs:
			return deserializeMapOfStructs(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_MapOfStructs, &v.MapOfStructs)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveList:
			return deserializeListOfKitchenSinks(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveList, &v.RecursiveList)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveMap:
			return deserializeMapOfKitchenSinks(d, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveMap, &v.RecursiveMap)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_RecursiveStruct:
			v.RecursiveStruct = &types.KitchenSink{}
			return v.RecursiveStruct.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_SimpleStruct:
			v.SimpleStruct = &types.SimpleStruct{}
			return v.SimpleStruct.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_String:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_String, &v.String_)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_StructWithJsonName:
			v.StructWithJsonName = &types.StructWithJsonName{}
			return v.StructWithJsonName.Deserialize(d)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Timestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_Timestamp, &v.Timestamp)
			case schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_UnixTimestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_KitchenSinkOperationOutput_UnixTimestamp, &v.UnixTimestamp)
		}
		return nil
	})
}
func (c *Client) addOperationKitchenSinkOperationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.KitchenSinkOperation, schemas.SmithyGoSynthetic_KitchenSinkOperationInput, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.KitchenSinkOperation, schemas.SmithyGoSynthetic_KitchenSinkOperationInput, schemas.SmithyGoSynthetic_KitchenSinkOperationOutput), output: &KitchenSinkOperationOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "KitchenSinkOperation"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opKitchenSinkOperation(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opKitchenSinkOperation(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "KitchenSinkOperation",
	}
}
