// Code generated by smithy-go-codegen DO NOT EDIT.

package accessanalyzer

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/service/accessanalyzer/types"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
)

// Creates a policy preview analysis job to evaluate the impact of Service Control
// Policies (SCPs) before deployment. The analysis uses historical CloudTrail
// authorization events to identify potential access denials, helping you prevent
// service disruptions.
//
// The job analyzes CloudTrail events within a specified time window and generates
// a report identifying which events would be denied by the proposed policy. The
// report is stored in the specified Amazon S3 location.
func (c *Client) StartPolicyPreviewJob(ctx context.Context, params *StartPolicyPreviewJobInput, optFns ...func(*Options)) (*StartPolicyPreviewJobOutput, error) {
	if params == nil {
		params = &StartPolicyPreviewJobInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "StartPolicyPreviewJob", params, optFns, c.addOperationStartPolicyPreviewJobMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*StartPolicyPreviewJobOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type StartPolicyPreviewJobInput struct {

	// The Amazon S3 URI where the completed analysis report will be stored. The
	// Amazon S3 bucket must grant access to the IAM Access Analyzer service principal
	// in its resource policy. The report will be stored at the path:
	// outputS3Uri/jobId/timestamp/ .
	//
	// This member is required.
	OutputS3Uri *string

	// A list of policy configurations to analyze. Currently limited to one
	// configuration per request. Each configuration specifies the job type, target ID,
	// and policy documents to test.
	//
	// This member is required.
	PolicyConfigurations []types.PolicyConfiguration

	// The start of the CloudTrail event analysis window. The analysis will evaluate
	// events from this time forward.
	//
	// This member is required.
	StartTime *time.Time

	// A unique, case-sensitive identifier that you provide to ensure the idempotency
	// of the request. Idempotency ensures that an API request completes only once.
	// With an idempotent request, if the original request completes successfully,
	// subsequent retries with the same client token return the result from the
	// original successful request and have no additional effect.
	ClientToken *string

	// The end of the analysis window. If not specified, defaults to the time of the
	// request. The analysis will evaluate CloudTrail events up to this time.
	EndTime *time.Time

	noSmithyDocumentSerde
}

type StartPolicyPreviewJobOutput struct {

	// The unique identifier for the created policy preview job. Use this ID with
	// GetPolicyPreviewJob to retrieve job status and details, or with
	// CancelPolicyPreviewJob to cancel the job.
	//
	// This member is required.
	JobId *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationStartPolicyPreviewJobMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	err = stack.Serialize.Add(&awsRestjson1_serializeOpStartPolicyPreviewJob{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsRestjson1_deserializeOpStartPolicyPreviewJob{}, middleware.After)
	if err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "StartPolicyPreviewJob"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options, c); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addIdempotencyToken_opStartPolicyPreviewJobMiddleware(stack, options); err != nil {
		return err
	}
	if err = addOpStartPolicyPreviewJobValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opStartPolicyPreviewJob(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

type idempotencyToken_initializeOpStartPolicyPreviewJob struct {
	tokenProvider IdempotencyTokenProvider
}

func (*idempotencyToken_initializeOpStartPolicyPreviewJob) ID() string {
	return "OperationIdempotencyTokenAutoFill"
}

func (m *idempotencyToken_initializeOpStartPolicyPreviewJob) HandleInitialize(ctx context.Context, in middleware.InitializeInput, next middleware.InitializeHandler) (
	out middleware.InitializeOutput, metadata middleware.Metadata, err error,
) {
	if m.tokenProvider == nil {
		return next.HandleInitialize(ctx, in)
	}

	input, ok := in.Parameters.(*StartPolicyPreviewJobInput)
	if !ok {
		return out, metadata, fmt.Errorf("expected middleware input to be of type *StartPolicyPreviewJobInput ")
	}

	if input.ClientToken == nil {
		t, err := m.tokenProvider.GetIdempotencyToken()
		if err != nil {
			return out, metadata, err
		}
		input.ClientToken = &t
	}
	return next.HandleInitialize(ctx, in)
}
func addIdempotencyToken_opStartPolicyPreviewJobMiddleware(stack *middleware.Stack, cfg Options) error {
	return stack.Initialize.Add(&idempotencyToken_initializeOpStartPolicyPreviewJob{tokenProvider: cfg.IdempotencyTokenProvider}, middleware.Before)
}

func newServiceMetadataMiddleware_opStartPolicyPreviewJob(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "StartPolicyPreviewJob",
	}
}
