// Code generated by smithy-go-codegen DO NOT EDIT.

package accessanalyzer

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/service/accessanalyzer/types"
	"github.com/aws/smithy-go/middleware"
	smithytime "github.com/aws/smithy-go/time"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	smithywaiter "github.com/aws/smithy-go/waiter"
	"time"
)

// Retrieves the metadata, parameters, and status for a policy preview job. Use
// this operation to monitor job progress and retrieve the Amazon S3 location of
// the completed analysis report.
//
// Job data has a time-to-live (TTL) of 14 days and will be deleted after
// expiration.
func (c *Client) GetPolicyPreviewJob(ctx context.Context, params *GetPolicyPreviewJobInput, optFns ...func(*Options)) (*GetPolicyPreviewJobOutput, error) {
	if params == nil {
		params = &GetPolicyPreviewJobInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "GetPolicyPreviewJob", params, optFns, c.addOperationGetPolicyPreviewJobMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*GetPolicyPreviewJobOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type GetPolicyPreviewJobInput struct {

	// The unique identifier of the policy preview job to retrieve. This is the job ID
	// returned by StartPolicyPreviewJob .
	//
	// This member is required.
	JobId *string

	noSmithyDocumentSerde
}

type GetPolicyPreviewJobOutput struct {

	// The unique identifier of the policy preview job.
	//
	// This member is required.
	JobId *string

	// The Amazon S3 URI where the analysis report is stored. The report contains
	// metadata for CloudTrail events that would be denied by the proposed policy.
	//
	// This member is required.
	OutputS3Uri *string

	// Details about the job execution, including current status, submission time,
	// start time, completion time, and any errors that occurred.
	JobDetails *types.PolicyPreviewJobDetails

	// The original parameters used to create the policy preview job, including the
	// analysis time window and policy configurations.
	JobParameters *types.PolicyPreviewJobParameters

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationGetPolicyPreviewJobMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	err = stack.Serialize.Add(&awsRestjson1_serializeOpGetPolicyPreviewJob{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsRestjson1_deserializeOpGetPolicyPreviewJob{}, middleware.After)
	if err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "GetPolicyPreviewJob"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options, c); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = addOpGetPolicyPreviewJobValidationMiddleware(stack); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opGetPolicyPreviewJob(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

// PolicyPreviewJobCompletedWaiterOptions are waiter options for
// PolicyPreviewJobCompletedWaiter
type PolicyPreviewJobCompletedWaiterOptions struct {

	// Set of options to modify how an operation is invoked. These apply to all
	// operations invoked for this client. Use functional options on operation call to
	// modify this list for per operation behavior.
	//
	// Passing options here is functionally equivalent to passing values to this
	// config's ClientOptions field that extend the inner client's APIOptions directly.
	APIOptions []func(*middleware.Stack) error

	// Functional options to be passed to all operations invoked by this client.
	//
	// Function values that modify the inner APIOptions are applied after the waiter
	// config's own APIOptions modifiers.
	ClientOptions []func(*Options)

	// MinDelay is the minimum amount of time to delay between retries. If unset,
	// PolicyPreviewJobCompletedWaiter will use default minimum delay of 30 seconds.
	// Note that MinDelay must resolve to a value lesser than or equal to the MaxDelay.
	MinDelay time.Duration

	// MaxDelay is the maximum amount of time to delay between retries. If unset or
	// set to zero, PolicyPreviewJobCompletedWaiter will use default max delay of 120
	// seconds. Note that MaxDelay must resolve to value greater than or equal to the
	// MinDelay.
	MaxDelay time.Duration

	// LogWaitAttempts is used to enable logging for waiter retry attempts
	LogWaitAttempts bool

	// Retryable is function that can be used to override the service defined
	// waiter-behavior based on operation output, or returned error. This function is
	// used by the waiter to decide if a state is retryable or a terminal state.
	//
	// By default service-modeled logic will populate this option. This option can
	// thus be used to define a custom waiter state with fall-back to service-modeled
	// waiter state mutators.The function returns an error in case of a failure state.
	// In case of retry state, this function returns a bool value of true and nil
	// error, while in case of success it returns a bool value of false and nil error.
	Retryable func(context.Context, *GetPolicyPreviewJobInput, *GetPolicyPreviewJobOutput, error) (bool, error)
}

// PolicyPreviewJobCompletedWaiter defines the waiters for
// PolicyPreviewJobCompleted
type PolicyPreviewJobCompletedWaiter struct {
	client GetPolicyPreviewJobAPIClient

	options PolicyPreviewJobCompletedWaiterOptions
}

// NewPolicyPreviewJobCompletedWaiter constructs a PolicyPreviewJobCompletedWaiter.
func NewPolicyPreviewJobCompletedWaiter(client GetPolicyPreviewJobAPIClient, optFns ...func(*PolicyPreviewJobCompletedWaiterOptions)) *PolicyPreviewJobCompletedWaiter {
	options := PolicyPreviewJobCompletedWaiterOptions{}
	options.MinDelay = 30 * time.Second
	options.MaxDelay = 120 * time.Second
	options.Retryable = policyPreviewJobCompletedStateRetryable

	for _, fn := range optFns {
		fn(&options)
	}
	return &PolicyPreviewJobCompletedWaiter{
		client:  client,
		options: options,
	}
}

// Wait calls the waiter function for PolicyPreviewJobCompleted waiter. The
// maxWaitDur is the maximum wait duration the waiter will wait. The maxWaitDur is
// required and must be greater than zero.
func (w *PolicyPreviewJobCompletedWaiter) Wait(ctx context.Context, params *GetPolicyPreviewJobInput, maxWaitDur time.Duration, optFns ...func(*PolicyPreviewJobCompletedWaiterOptions)) error {
	_, err := w.WaitForOutput(ctx, params, maxWaitDur, optFns...)
	return err
}

// WaitForOutput calls the waiter function for PolicyPreviewJobCompleted waiter
// and returns the output of the successful operation. The maxWaitDur is the
// maximum wait duration the waiter will wait. The maxWaitDur is required and must
// be greater than zero.
func (w *PolicyPreviewJobCompletedWaiter) WaitForOutput(ctx context.Context, params *GetPolicyPreviewJobInput, maxWaitDur time.Duration, optFns ...func(*PolicyPreviewJobCompletedWaiterOptions)) (*GetPolicyPreviewJobOutput, error) {
	if maxWaitDur <= 0 {
		return nil, fmt.Errorf("maximum wait time for waiter must be greater than zero")
	}

	options := w.options
	for _, fn := range optFns {
		fn(&options)
	}

	if options.MaxDelay <= 0 {
		options.MaxDelay = 120 * time.Second
	}

	if options.MinDelay > options.MaxDelay {
		return nil, fmt.Errorf("minimum waiter delay %v must be lesser than or equal to maximum waiter delay of %v.", options.MinDelay, options.MaxDelay)
	}

	ctx, cancelFn := context.WithTimeout(ctx, maxWaitDur)
	defer cancelFn()

	logger := smithywaiter.Logger{}
	remainingTime := maxWaitDur

	var attempt int64
	for {

		attempt++
		apiOptions := options.APIOptions
		start := time.Now()

		if options.LogWaitAttempts {
			logger.Attempt = attempt
			apiOptions = append([]func(*middleware.Stack) error{}, options.APIOptions...)
			apiOptions = append(apiOptions, logger.AddLogger)
		}

		out, err := w.client.GetPolicyPreviewJob(ctx, params, func(o *Options) {
			baseOpts := []func(*Options){
				addIsWaiterUserAgent,
			}
			o.APIOptions = append(o.APIOptions, apiOptions...)
			for _, opt := range baseOpts {
				opt(o)
			}
			for _, opt := range options.ClientOptions {
				opt(o)
			}
		})

		retryable, err := options.Retryable(ctx, params, out, err)
		if err != nil {
			return nil, err
		}
		if !retryable {
			return out, nil
		}

		remainingTime -= time.Since(start)
		if remainingTime < options.MinDelay || remainingTime <= 0 {
			break
		}

		// compute exponential backoff between waiter retries
		delay, err := smithywaiter.ComputeDelay(
			attempt, options.MinDelay, options.MaxDelay, remainingTime,
		)
		if err != nil {
			return nil, fmt.Errorf("error computing waiter delay, %w", err)
		}

		remainingTime -= delay
		// sleep for the delay amount before invoking a request
		if err := smithytime.SleepWithContext(ctx, delay); err != nil {
			return nil, fmt.Errorf("request cancelled while waiting, %w", err)
		}
	}
	return nil, fmt.Errorf("exceeded max wait time for PolicyPreviewJobCompleted waiter")
}

func policyPreviewJobCompletedStateRetryable(ctx context.Context, input *GetPolicyPreviewJobInput, output *GetPolicyPreviewJobOutput, err error) (bool, error) {

	if err == nil {
		v1 := output.JobDetails
		var v2 types.ImpactAnalysisJobStatus
		if v1 != nil {
			v3 := v1.JobStatus
			v2 = v3
		}
		expectedValue := "COMPLETED"
		var pathValue string
		pathValue = string(v2)
		if pathValue == expectedValue {
			return false, nil
		}
	}

	if err == nil {
		v1 := output.JobDetails
		var v2 types.ImpactAnalysisJobStatus
		if v1 != nil {
			v3 := v1.JobStatus
			v2 = v3
		}
		expectedValue := "FAILED"
		var pathValue string
		pathValue = string(v2)
		if pathValue == expectedValue {
			return false, fmt.Errorf("waiter state transitioned to Failure")
		}
	}

	if err == nil {
		v1 := output.JobDetails
		var v2 types.ImpactAnalysisJobStatus
		if v1 != nil {
			v3 := v1.JobStatus
			v2 = v3
		}
		expectedValue := "CANCELED"
		var pathValue string
		pathValue = string(v2)
		if pathValue == expectedValue {
			return false, fmt.Errorf("waiter state transitioned to Failure")
		}
	}

	if err != nil {
		return false, err
	}
	return true, nil
}

// GetPolicyPreviewJobAPIClient is a client that implements the
// GetPolicyPreviewJob operation.
type GetPolicyPreviewJobAPIClient interface {
	GetPolicyPreviewJob(context.Context, *GetPolicyPreviewJobInput, ...func(*Options)) (*GetPolicyPreviewJobOutput, error)
}

var _ GetPolicyPreviewJobAPIClient = (*Client)(nil)

func newServiceMetadataMiddleware_opGetPolicyPreviewJob(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "GetPolicyPreviewJob",
	}
}
