// Code generated by smithy-go-codegen DO NOT EDIT.

package accessanalyzer

import (
	"context"
	"fmt"
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"github.com/aws/aws-sdk-go-v2/service/accessanalyzer/types"
	"github.com/aws/smithy-go/middleware"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Lists all policy preview jobs with optional filtering by job status or target
// ID. Results are paginated for efficient retrieval of large result sets.
func (c *Client) ListPolicyPreviewJobs(ctx context.Context, params *ListPolicyPreviewJobsInput, optFns ...func(*Options)) (*ListPolicyPreviewJobsOutput, error) {
	if params == nil {
		params = &ListPolicyPreviewJobsInput{}
	}

	result, metadata, err := c.invokeOperation(ctx, "ListPolicyPreviewJobs", params, optFns, c.addOperationListPolicyPreviewJobsMiddlewares)
	if err != nil {
		return nil, err
	}

	out := result.(*ListPolicyPreviewJobsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type ListPolicyPreviewJobsInput struct {

	// Optional filter criteria to narrow the list of returned jobs. You can filter by
	// job status or target ID. Maximum of one filter can be specified.
	Filters map[string]string

	// The maximum number of results to return in a single page. Minimum value is 1.
	MaxResults *int32

	// A token used for pagination of results. Use the token returned in the previous
	// response to retrieve the next page of results.
	NextToken *string

	noSmithyDocumentSerde
}

type ListPolicyPreviewJobsOutput struct {

	// A list of policy preview job summaries that match the specified filter criteria.
	//
	// This member is required.
	AnalysisReports []types.PolicyPreviewAnalysisReport

	// A token used for pagination. If present, indicates there are more results
	// available. Pass this token to the next request to retrieve the next page.
	NextToken *string

	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata

	noSmithyDocumentSerde
}

func (c *Client) addOperationListPolicyPreviewJobsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
		return err
	}
	err = stack.Serialize.Add(&awsRestjson1_serializeOpListPolicyPreviewJobs{}, middleware.After)
	if err != nil {
		return err
	}
	err = stack.Deserialize.Add(&awsRestjson1_deserializeOpListPolicyPreviewJobs{}, middleware.After)
	if err != nil {
		return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "ListPolicyPreviewJobs"); err != nil {
		return fmt.Errorf("add protocol finalizers: %v", err)
	}

	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
		return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
		return err
	}
	if err = addClientRequestID(stack); err != nil {
		return err
	}
	if err = addComputeContentLength(stack); err != nil {
		return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
		return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
		return err
	}
	if err = addRetry(stack, options, c); err != nil {
		return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
		return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
		return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
		return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
		return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
		return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
		return err
	}
	if err = addCredentialSource(stack, options); err != nil {
		return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opListPolicyPreviewJobs(options.Region), middleware.Before); err != nil {
		return err
	}
	if err = addRecursionDetection(stack); err != nil {
		return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
		return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
		return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
		return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
		return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
		return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
		return err
	}
	if err = addInterceptors(stack, options); err != nil {
		return err
	}
	return nil
}

// ListPolicyPreviewJobsPaginatorOptions is the paginator options for
// ListPolicyPreviewJobs
type ListPolicyPreviewJobsPaginatorOptions struct {
	// The maximum number of results to return in a single page. Minimum value is 1.
	Limit int32

	// Set to true if pagination should stop if the service returns a pagination token
	// that matches the most recent token provided to the service.
	StopOnDuplicateToken bool
}

// ListPolicyPreviewJobsPaginator is a paginator for ListPolicyPreviewJobs
type ListPolicyPreviewJobsPaginator struct {
	options   ListPolicyPreviewJobsPaginatorOptions
	client    ListPolicyPreviewJobsAPIClient
	params    *ListPolicyPreviewJobsInput
	nextToken *string
	firstPage bool
}

// NewListPolicyPreviewJobsPaginator returns a new ListPolicyPreviewJobsPaginator
func NewListPolicyPreviewJobsPaginator(client ListPolicyPreviewJobsAPIClient, params *ListPolicyPreviewJobsInput, optFns ...func(*ListPolicyPreviewJobsPaginatorOptions)) *ListPolicyPreviewJobsPaginator {
	if params == nil {
		params = &ListPolicyPreviewJobsInput{}
	}

	options := ListPolicyPreviewJobsPaginatorOptions{}
	if params.MaxResults != nil {
		options.Limit = *params.MaxResults
	}

	for _, fn := range optFns {
		fn(&options)
	}

	return &ListPolicyPreviewJobsPaginator{
		options:   options,
		client:    client,
		params:    params,
		firstPage: true,
		nextToken: params.NextToken,
	}
}

// HasMorePages returns a boolean indicating whether more pages are available
func (p *ListPolicyPreviewJobsPaginator) HasMorePages() bool {
	return p.firstPage || (p.nextToken != nil && len(*p.nextToken) != 0)
}

// NextPage retrieves the next ListPolicyPreviewJobs page.
func (p *ListPolicyPreviewJobsPaginator) NextPage(ctx context.Context, optFns ...func(*Options)) (*ListPolicyPreviewJobsOutput, error) {
	if !p.HasMorePages() {
		return nil, fmt.Errorf("no more pages available")
	}

	params := *p.params
	params.NextToken = p.nextToken

	var limit *int32
	if p.options.Limit > 0 {
		limit = &p.options.Limit
	}
	params.MaxResults = limit

	optFns = append([]func(*Options){
		addIsPaginatorUserAgent,
	}, optFns...)
	result, err := p.client.ListPolicyPreviewJobs(ctx, &params, optFns...)
	if err != nil {
		return nil, err
	}
	p.firstPage = false

	prevToken := p.nextToken
	p.nextToken = result.NextToken

	if p.options.StopOnDuplicateToken &&
		prevToken != nil &&
		p.nextToken != nil &&
		*prevToken == *p.nextToken {
		p.nextToken = nil
	}

	return result, nil
}

// ListPolicyPreviewJobsAPIClient is a client that implements the
// ListPolicyPreviewJobs operation.
type ListPolicyPreviewJobsAPIClient interface {
	ListPolicyPreviewJobs(context.Context, *ListPolicyPreviewJobsInput, ...func(*Options)) (*ListPolicyPreviewJobsOutput, error)
}

var _ ListPolicyPreviewJobsAPIClient = (*Client)(nil)

func newServiceMetadataMiddleware_opListPolicyPreviewJobs(region string) *awsmiddleware.RegisterServiceMetadata {
	return &awsmiddleware.RegisterServiceMetadata{
		Region:        region,
		ServiceID:     ServiceID,
		OperationName: "ListPolicyPreviewJobs",
	}
}
