// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
)

// This example tests how timestamp request and response headers are serialized.
func (c *Client) TimestampFormatHeaders(ctx context.Context, params *TimestampFormatHeadersInput, optFns ...func(*Options)) (*TimestampFormatHeadersOutput, error) {
	if params == nil { params = &TimestampFormatHeadersInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "TimestampFormatHeaders", params, optFns, c.addOperationTimestampFormatHeadersMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*TimestampFormatHeadersOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type TimestampFormatHeadersInput struct {
	
	DefaultFormat *time.Time
	
	MemberDateTime *time.Time
	
	MemberEpochSeconds *time.Time
	
	MemberHttpDate *time.Time
	
	TargetDateTime *time.Time
	
	TargetEpochSeconds *time.Time
	
	TargetHttpDate *time.Time
	
	noSmithyDocumentSerde
}

func (v *TimestampFormatHeadersInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_defaultFormat, v.DefaultFormat)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberDateTime, v.MemberDateTime)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberEpochSeconds, v.MemberEpochSeconds)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberHttpDate, v.MemberHttpDate)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetDateTime, v.TargetDateTime)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetEpochSeconds, v.TargetEpochSeconds)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetHttpDate, v.TargetHttpDate)
	s.CloseMap()
}
func (v *TimestampFormatHeadersInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_TimestampFormatHeadersInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_defaultFormat:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_defaultFormat, &v.DefaultFormat)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberDateTime:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberDateTime, &v.MemberDateTime)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberEpochSeconds:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberEpochSeconds, &v.MemberEpochSeconds)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberHttpDate:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_memberHttpDate, &v.MemberHttpDate)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetDateTime:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetDateTime, &v.TargetDateTime)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetEpochSeconds:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetEpochSeconds, &v.TargetEpochSeconds)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetHttpDate:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersInput_targetHttpDate, &v.TargetHttpDate)
		}
		return nil
	})
}
type TimestampFormatHeadersOutput struct {
	
	DefaultFormat *time.Time
	
	MemberDateTime *time.Time
	
	MemberEpochSeconds *time.Time
	
	MemberHttpDate *time.Time
	
	TargetDateTime *time.Time
	
	TargetEpochSeconds *time.Time
	
	TargetHttpDate *time.Time
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *TimestampFormatHeadersOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_defaultFormat, v.DefaultFormat)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberDateTime, v.MemberDateTime)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberEpochSeconds, v.MemberEpochSeconds)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberHttpDate, v.MemberHttpDate)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetDateTime, v.TargetDateTime)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetEpochSeconds, v.TargetEpochSeconds)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetHttpDate, v.TargetHttpDate)
	s.CloseMap()
}
func (v *TimestampFormatHeadersOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_defaultFormat:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_defaultFormat, &v.DefaultFormat)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberDateTime:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberDateTime, &v.MemberDateTime)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberEpochSeconds:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberEpochSeconds, &v.MemberEpochSeconds)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberHttpDate:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_memberHttpDate, &v.MemberHttpDate)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetDateTime:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetDateTime, &v.TargetDateTime)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetEpochSeconds:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetEpochSeconds, &v.TargetEpochSeconds)
			case schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetHttpDate:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput_targetHttpDate, &v.TargetHttpDate)
		}
		return nil
	})
}
func (c *Client) addOperationTimestampFormatHeadersMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.TimestampFormatHeaders, schemas.SmithyGoSynthetic_TimestampFormatHeadersInput, schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.TimestampFormatHeaders, schemas.SmithyGoSynthetic_TimestampFormatHeadersInput, schemas.SmithyGoSynthetic_TimestampFormatHeadersOutput), output: &TimestampFormatHeadersOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "TimestampFormatHeaders"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opTimestampFormatHeaders(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opTimestampFormatHeaders(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "TimestampFormatHeaders",
	}
}
