// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/document"
	"fmt"
	internaldocument "github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/internal/document"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithydocument "github.com/aws/smithy-go/document"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This example serializes a document as the entire HTTP payload.
func (c *Client) DocumentTypeAsPayload(ctx context.Context, params *DocumentTypeAsPayloadInput, optFns ...func(*Options)) (*DocumentTypeAsPayloadOutput, error) {
	if params == nil { params = &DocumentTypeAsPayloadInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "DocumentTypeAsPayload", params, optFns, c.addOperationDocumentTypeAsPayloadMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*DocumentTypeAsPayloadOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type DocumentTypeAsPayloadInput struct {
	
	DocumentValue document.Interface
	
	noSmithyDocumentSerde
}

func (v *DocumentTypeAsPayloadInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput)
	s.WriteDocument(schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput_documentValue, &smithydocument.Opaque{Value: v.DocumentValue})
	s.CloseMap()
}
func (v *DocumentTypeAsPayloadInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput_documentValue:
			var dv smithydocument.Value
			if err := d.ReadDocument(schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput_documentValue, &dv); err != nil {
			    return err
			}
			if ov, ok := dv.(smithydocument.Opaque); ok {
			    v.DocumentValue = internaldocument.NewDocumentUnmarshaler(ov.Value)
			}
			return nil
		}
		return nil
	})
}
type DocumentTypeAsPayloadOutput struct {
	
	DocumentValue document.Interface
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *DocumentTypeAsPayloadOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput)
	s.WriteDocument(schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput_documentValue, &smithydocument.Opaque{Value: v.DocumentValue})
	s.CloseMap()
}
func (v *DocumentTypeAsPayloadOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput_documentValue:
			var dv smithydocument.Value
			if err := d.ReadDocument(schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput_documentValue, &dv); err != nil {
			    return err
			}
			if ov, ok := dv.(smithydocument.Opaque); ok {
			    v.DocumentValue = internaldocument.NewDocumentUnmarshaler(ov.Value)
			}
			return nil
		}
		return nil
	})
}
func (c *Client) addOperationDocumentTypeAsPayloadMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.DocumentTypeAsPayload, schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput, schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.DocumentTypeAsPayload, schemas.SmithyGoSynthetic_DocumentTypeAsPayloadInput, schemas.SmithyGoSynthetic_DocumentTypeAsPayloadOutput), output: &DocumentTypeAsPayloadOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "DocumentTypeAsPayload"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opDocumentTypeAsPayload(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opDocumentTypeAsPayload(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "DocumentTypeAsPayload",
	}
}
