// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Null headers are not sent over the wire, empty headers are serialized to ""
func (c *Client) NullAndEmptyHeadersClient(ctx context.Context, params *NullAndEmptyHeadersClientInput, optFns ...func(*Options)) (*NullAndEmptyHeadersClientOutput, error) {
	if params == nil { params = &NullAndEmptyHeadersClientInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "NullAndEmptyHeadersClient", params, optFns, c.addOperationNullAndEmptyHeadersClientMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*NullAndEmptyHeadersClientOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type NullAndEmptyHeadersClientInput struct {
	
	A *string
	
	B *string
	
	C []string
	
	noSmithyDocumentSerde
}

func (v *NullAndEmptyHeadersClientInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_a, v.A)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_b, v.B)
	serializeStringList(s, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_c, v.C)
	s.CloseMap()
}
func (v *NullAndEmptyHeadersClientInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_a:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_a, &v.A)
			case schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_b:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_b, &v.B)
			case schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_c:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput_c, &v.C)
		}
		return nil
	})
}
type NullAndEmptyHeadersClientOutput struct {
	
	A *string
	
	B *string
	
	C []string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *NullAndEmptyHeadersClientOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_a, v.A)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_b, v.B)
	serializeStringList(s, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_c, v.C)
	s.CloseMap()
}
func (v *NullAndEmptyHeadersClientOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_a:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_a, &v.A)
			case schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_b:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_b, &v.B)
			case schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_c:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput_c, &v.C)
		}
		return nil
	})
}
func (c *Client) addOperationNullAndEmptyHeadersClientMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.NullAndEmptyHeadersClient, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.NullAndEmptyHeadersClient, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientInput, schemas.SmithyGoSynthetic_NullAndEmptyHeadersClientOutput), output: &NullAndEmptyHeadersClientOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "NullAndEmptyHeadersClient"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opNullAndEmptyHeadersClient(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opNullAndEmptyHeadersClient(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "NullAndEmptyHeadersClient",
	}
}
