// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Clients that perform this test extract all headers from the response.
func (c *Client) HttpEmptyPrefixHeaders(ctx context.Context, params *HttpEmptyPrefixHeadersInput, optFns ...func(*Options)) (*HttpEmptyPrefixHeadersOutput, error) {
	if params == nil { params = &HttpEmptyPrefixHeadersInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "HttpEmptyPrefixHeaders", params, optFns, c.addOperationHttpEmptyPrefixHeadersMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*HttpEmptyPrefixHeadersOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type HttpEmptyPrefixHeadersInput struct {
	
	PrefixHeaders map[string]string
	
	SpecificHeader *string
	
	noSmithyDocumentSerde
}

func (v *HttpEmptyPrefixHeadersInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersInput)
	serializeStringMap(s, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersInput_prefixHeaders, v.PrefixHeaders)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersInput_specificHeader, v.SpecificHeader)
	s.CloseMap()
}
type HttpEmptyPrefixHeadersOutput struct {
	
	// Map keys will be normalized to lower-case.
	PrefixHeaders map[string]string
	
	SpecificHeader *string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *HttpEmptyPrefixHeadersOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput_prefixHeaders:
			return deserializeStringMap(d, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput_prefixHeaders, &v.PrefixHeaders)
			case schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput_specificHeader:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput_specificHeader, &v.SpecificHeader)
		}
		return nil
	})
}
func (c *Client) addOperationHttpEmptyPrefixHeadersMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpEmptyPrefixHeaders, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersInput, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpEmptyPrefixHeaders, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersInput, schemas.SmithyGoSynthetic_HttpEmptyPrefixHeadersOutput), output: &HttpEmptyPrefixHeadersOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "HttpEmptyPrefixHeaders"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opHttpEmptyPrefixHeaders(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opHttpEmptyPrefixHeaders(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "HttpEmptyPrefixHeaders",
	}
}
