// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) MalformedContentTypeWithGenericString(ctx context.Context, params *MalformedContentTypeWithGenericStringInput, optFns ...func(*Options)) (*MalformedContentTypeWithGenericStringOutput, error) {
	if params == nil { params = &MalformedContentTypeWithGenericStringInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "MalformedContentTypeWithGenericString", params, optFns, c.addOperationMalformedContentTypeWithGenericStringMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*MalformedContentTypeWithGenericStringOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type MalformedContentTypeWithGenericStringInput struct {
	
	Payload *string
	
	noSmithyDocumentSerde
}

func (v *MalformedContentTypeWithGenericStringInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput_payload, v.Payload)
	s.CloseMap()
}
func (v *MalformedContentTypeWithGenericStringInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput_payload:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput_payload, &v.Payload)
		}
		return nil
	})
}
type MalformedContentTypeWithGenericStringOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *MalformedContentTypeWithGenericStringOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringOutput)
	s.CloseMap()
}
func (v *MalformedContentTypeWithGenericStringOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationMalformedContentTypeWithGenericStringMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedContentTypeWithGenericString, schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput, schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedContentTypeWithGenericString, schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringInput, schemas.SmithyGoSynthetic_MalformedContentTypeWithGenericStringOutput), output: &MalformedContentTypeWithGenericStringOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "MalformedContentTypeWithGenericString"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opMalformedContentTypeWithGenericString(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opMalformedContentTypeWithGenericString(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "MalformedContentTypeWithGenericString",
	}
}
