// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) QueryParamsAsStringListMap(ctx context.Context, params *QueryParamsAsStringListMapInput, optFns ...func(*Options)) (*QueryParamsAsStringListMapOutput, error) {
	if params == nil { params = &QueryParamsAsStringListMapInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "QueryParamsAsStringListMap", params, optFns, c.addOperationQueryParamsAsStringListMapMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*QueryParamsAsStringListMapOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type QueryParamsAsStringListMapInput struct {
	
	Foo map[string][]string
	
	Qux *string
	
	noSmithyDocumentSerde
}

func (v *QueryParamsAsStringListMapInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput)
	serializeStringListMap(s, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput_foo, v.Foo)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput_qux, v.Qux)
	s.CloseMap()
}
func (v *QueryParamsAsStringListMapInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput_foo:
			return deserializeStringListMap(d, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput_foo, &v.Foo)
			case schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput_qux:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput_qux, &v.Qux)
		}
		return nil
	})
}
type QueryParamsAsStringListMapOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *QueryParamsAsStringListMapOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_QueryParamsAsStringListMapOutput)
	s.CloseMap()
}
func (v *QueryParamsAsStringListMapOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationQueryParamsAsStringListMapMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.QueryParamsAsStringListMap, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.QueryParamsAsStringListMap, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapInput, schemas.SmithyGoSynthetic_QueryParamsAsStringListMapOutput), output: &QueryParamsAsStringListMapOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "QueryParamsAsStringListMap"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opQueryParamsAsStringListMap(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opQueryParamsAsStringListMap(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "QueryParamsAsStringListMap",
	}
}
