// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) MalformedShort(ctx context.Context, params *MalformedShortInput, optFns ...func(*Options)) (*MalformedShortOutput, error) {
	if params == nil { params = &MalformedShortInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "MalformedShort", params, optFns, c.addOperationMalformedShortMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*MalformedShortOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type MalformedShortInput struct {
	
	// This member is required.
	ShortInPath *int16
	
	ShortInBody *int16
	
	ShortInHeader *int16
	
	ShortInQuery *int16
	
	noSmithyDocumentSerde
}

func (v *MalformedShortInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedShortInput)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInBody, v.ShortInBody)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInHeader, v.ShortInHeader)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInPath, v.ShortInPath)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInQuery, v.ShortInQuery)
	s.CloseMap()
}
func (v *MalformedShortInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedShortInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_MalformedShortInput_shortInBody:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInBody, &v.ShortInBody)
			case schemas.SmithyGoSynthetic_MalformedShortInput_shortInHeader:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInHeader, &v.ShortInHeader)
			case schemas.SmithyGoSynthetic_MalformedShortInput_shortInPath:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInPath, &v.ShortInPath)
			case schemas.SmithyGoSynthetic_MalformedShortInput_shortInQuery:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_MalformedShortInput_shortInQuery, &v.ShortInQuery)
		}
		return nil
	})
}
type MalformedShortOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *MalformedShortOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedShortOutput)
	s.CloseMap()
}
func (v *MalformedShortOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedShortOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationMalformedShortMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedShort, schemas.SmithyGoSynthetic_MalformedShortInput, schemas.SmithyGoSynthetic_MalformedShortOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedShort, schemas.SmithyGoSynthetic_MalformedShortInput, schemas.SmithyGoSynthetic_MalformedShortOutput), output: &MalformedShortOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "MalformedShort"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = addOpMalformedShortValidationMiddleware(stack); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opMalformedShort(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opMalformedShort(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "MalformedShort",
	}
}
