// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) MalformedByte(ctx context.Context, params *MalformedByteInput, optFns ...func(*Options)) (*MalformedByteOutput, error) {
	if params == nil { params = &MalformedByteInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "MalformedByte", params, optFns, c.addOperationMalformedByteMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*MalformedByteOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type MalformedByteInput struct {
	
	// This member is required.
	ByteInPath *int8
	
	ByteInBody *int8
	
	ByteInHeader *int8
	
	ByteInQuery *int8
	
	noSmithyDocumentSerde
}

func (v *MalformedByteInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedByteInput)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInBody, v.ByteInBody)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInHeader, v.ByteInHeader)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInPath, v.ByteInPath)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInQuery, v.ByteInQuery)
	s.CloseMap()
}
func (v *MalformedByteInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedByteInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_MalformedByteInput_byteInBody:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInBody, &v.ByteInBody)
			case schemas.SmithyGoSynthetic_MalformedByteInput_byteInHeader:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInHeader, &v.ByteInHeader)
			case schemas.SmithyGoSynthetic_MalformedByteInput_byteInPath:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInPath, &v.ByteInPath)
			case schemas.SmithyGoSynthetic_MalformedByteInput_byteInQuery:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_MalformedByteInput_byteInQuery, &v.ByteInQuery)
		}
		return nil
	})
}
type MalformedByteOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *MalformedByteOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedByteOutput)
	s.CloseMap()
}
func (v *MalformedByteOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedByteOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationMalformedByteMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedByte, schemas.SmithyGoSynthetic_MalformedByteInput, schemas.SmithyGoSynthetic_MalformedByteOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedByte, schemas.SmithyGoSynthetic_MalformedByteInput, schemas.SmithyGoSynthetic_MalformedByteOutput), output: &MalformedByteOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "MalformedByte"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = addOpMalformedByteValidationMiddleware(stack); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opMalformedByte(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opMalformedByte(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "MalformedByte",
	}
}
