// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/types"
)

// This example serializes a union in the payload.
func (c *Client) HttpPayloadWithUnion(ctx context.Context, params *HttpPayloadWithUnionInput, optFns ...func(*Options)) (*HttpPayloadWithUnionOutput, error) {
	if params == nil { params = &HttpPayloadWithUnionInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "HttpPayloadWithUnion", params, optFns, c.addOperationHttpPayloadWithUnionMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*HttpPayloadWithUnionOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type HttpPayloadWithUnionInput struct {
	
	Nested types.UnionPayload
	
	noSmithyDocumentSerde
}

func (v *HttpPayloadWithUnionInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput)
	serializeUnionPayload(s, schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput_nested, v.Nested)
	s.CloseMap()
}
func (v *HttpPayloadWithUnionInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput_nested:
			return deserializeUnionPayload(d, schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput_nested, &v.Nested)
		}
		return nil
	})
}
type HttpPayloadWithUnionOutput struct {
	
	Nested types.UnionPayload
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *HttpPayloadWithUnionOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput)
	serializeUnionPayload(s, schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput_nested, v.Nested)
	s.CloseMap()
}
func (v *HttpPayloadWithUnionOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput_nested:
			return deserializeUnionPayload(d, schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput_nested, &v.Nested)
		}
		return nil
	})
}
func (c *Client) addOperationHttpPayloadWithUnionMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpPayloadWithUnion, schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput, schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpPayloadWithUnion, schemas.SmithyGoSynthetic_HttpPayloadWithUnionInput, schemas.SmithyGoSynthetic_HttpPayloadWithUnionOutput), output: &HttpPayloadWithUnionOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "HttpPayloadWithUnion"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opHttpPayloadWithUnion(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opHttpPayloadWithUnion(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "HttpPayloadWithUnion",
	}
}
