// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/document"
	"fmt"
	internaldocument "github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/internal/document"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithydocument "github.com/aws/smithy-go/document"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This example serializes a document as part of the payload.
func (c *Client) DocumentType(ctx context.Context, params *DocumentTypeInput, optFns ...func(*Options)) (*DocumentTypeOutput, error) {
	if params == nil { params = &DocumentTypeInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "DocumentType", params, optFns, c.addOperationDocumentTypeMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*DocumentTypeOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type DocumentTypeInput struct {
	
	DocumentValue document.Interface
	
	StringValue *string
	
	noSmithyDocumentSerde
}

func (v *DocumentTypeInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_DocumentTypeInput)
	s.WriteDocument(schemas.SmithyGoSynthetic_DocumentTypeInput_documentValue, &smithydocument.Opaque{Value: v.DocumentValue})
	s.WriteStringPtr(schemas.SmithyGoSynthetic_DocumentTypeInput_stringValue, v.StringValue)
	s.CloseMap()
}
func (v *DocumentTypeInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_DocumentTypeInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_DocumentTypeInput_documentValue:
			var dv smithydocument.Value
			if err := d.ReadDocument(schemas.SmithyGoSynthetic_DocumentTypeInput_documentValue, &dv); err != nil {
			    return err
			}
			if ov, ok := dv.(smithydocument.Opaque); ok {
			    v.DocumentValue = internaldocument.NewDocumentUnmarshaler(ov.Value)
			}
			return nil
			case schemas.SmithyGoSynthetic_DocumentTypeInput_stringValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_DocumentTypeInput_stringValue, &v.StringValue)
		}
		return nil
	})
}
type DocumentTypeOutput struct {
	
	DocumentValue document.Interface
	
	StringValue *string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *DocumentTypeOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_DocumentTypeOutput)
	s.WriteDocument(schemas.SmithyGoSynthetic_DocumentTypeOutput_documentValue, &smithydocument.Opaque{Value: v.DocumentValue})
	s.WriteStringPtr(schemas.SmithyGoSynthetic_DocumentTypeOutput_stringValue, v.StringValue)
	s.CloseMap()
}
func (v *DocumentTypeOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_DocumentTypeOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_DocumentTypeOutput_documentValue:
			var dv smithydocument.Value
			if err := d.ReadDocument(schemas.SmithyGoSynthetic_DocumentTypeOutput_documentValue, &dv); err != nil {
			    return err
			}
			if ov, ok := dv.(smithydocument.Opaque); ok {
			    v.DocumentValue = internaldocument.NewDocumentUnmarshaler(ov.Value)
			}
			return nil
			case schemas.SmithyGoSynthetic_DocumentTypeOutput_stringValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_DocumentTypeOutput_stringValue, &v.StringValue)
		}
		return nil
	})
}
func (c *Client) addOperationDocumentTypeMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.DocumentType, schemas.SmithyGoSynthetic_DocumentTypeInput, schemas.SmithyGoSynthetic_DocumentTypeOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.DocumentType, schemas.SmithyGoSynthetic_DocumentTypeInput, schemas.SmithyGoSynthetic_DocumentTypeOutput), output: &DocumentTypeOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "DocumentType"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opDocumentType(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opDocumentType(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "DocumentType",
	}
}
