// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) SimpleScalarProperties(ctx context.Context, params *SimpleScalarPropertiesInput, optFns ...func(*Options)) (*SimpleScalarPropertiesOutput, error) {
	if params == nil { params = &SimpleScalarPropertiesInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "SimpleScalarProperties", params, optFns, c.addOperationSimpleScalarPropertiesMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*SimpleScalarPropertiesOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type SimpleScalarPropertiesInput struct {
	
	ByteValue *int8
	
	DoubleValue *float64
	
	FalseBooleanValue *bool
	
	FloatValue *float32
	
	Foo *string
	
	IntegerValue *int32
	
	LongValue *int64
	
	ShortValue *int16
	
	StringValue *string
	
	TrueBooleanValue *bool
	
	noSmithyDocumentSerde
}

func (v *SimpleScalarPropertiesInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_byteValue, v.ByteValue)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_doubleValue, v.DoubleValue)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_falseBooleanValue, v.FalseBooleanValue)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_floatValue, v.FloatValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_foo, v.Foo)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_integerValue, v.IntegerValue)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_longValue, v.LongValue)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_shortValue, v.ShortValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_stringValue, v.StringValue)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_trueBooleanValue, v.TrueBooleanValue)
	s.CloseMap()
}
func (v *SimpleScalarPropertiesInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_byteValue:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_byteValue, &v.ByteValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_doubleValue:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_doubleValue, &v.DoubleValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_falseBooleanValue:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_falseBooleanValue, &v.FalseBooleanValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_floatValue:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_floatValue, &v.FloatValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_foo, &v.Foo)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_integerValue:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_integerValue, &v.IntegerValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_longValue:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_longValue, &v.LongValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_shortValue:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_shortValue, &v.ShortValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_stringValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_stringValue, &v.StringValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_trueBooleanValue:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput_trueBooleanValue, &v.TrueBooleanValue)
		}
		return nil
	})
}
type SimpleScalarPropertiesOutput struct {
	
	ByteValue *int8
	
	DoubleValue *float64
	
	FalseBooleanValue *bool
	
	FloatValue *float32
	
	Foo *string
	
	IntegerValue *int32
	
	LongValue *int64
	
	ShortValue *int16
	
	StringValue *string
	
	TrueBooleanValue *bool
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *SimpleScalarPropertiesOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_byteValue, v.ByteValue)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_doubleValue, v.DoubleValue)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_falseBooleanValue, v.FalseBooleanValue)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_floatValue, v.FloatValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_foo, v.Foo)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_integerValue, v.IntegerValue)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_longValue, v.LongValue)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_shortValue, v.ShortValue)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_stringValue, v.StringValue)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_trueBooleanValue, v.TrueBooleanValue)
	s.CloseMap()
}
func (v *SimpleScalarPropertiesOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_byteValue:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_byteValue, &v.ByteValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_doubleValue:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_doubleValue, &v.DoubleValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_falseBooleanValue:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_falseBooleanValue, &v.FalseBooleanValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_floatValue:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_floatValue, &v.FloatValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_foo, &v.Foo)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_integerValue:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_integerValue, &v.IntegerValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_longValue:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_longValue, &v.LongValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_shortValue:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_shortValue, &v.ShortValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_stringValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_stringValue, &v.StringValue)
			case schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_trueBooleanValue:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput_trueBooleanValue, &v.TrueBooleanValue)
		}
		return nil
	})
}
func (c *Client) addOperationSimpleScalarPropertiesMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleScalarProperties, schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput, schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SimpleScalarProperties, schemas.SmithyGoSynthetic_SimpleScalarPropertiesInput, schemas.SmithyGoSynthetic_SimpleScalarPropertiesOutput), output: &SimpleScalarPropertiesOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "SimpleScalarProperties"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opSimpleScalarProperties(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opSimpleScalarProperties(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "SimpleScalarProperties",
	}
}
