// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/types"
)

// The example tests how requests and responses are serialized when there is no
// input or output payload but there are HTTP header bindings.
func (c *Client) InputAndOutputWithHeaders(ctx context.Context, params *InputAndOutputWithHeadersInput, optFns ...func(*Options)) (*InputAndOutputWithHeadersOutput, error) {
	if params == nil { params = &InputAndOutputWithHeadersInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "InputAndOutputWithHeaders", params, optFns, c.addOperationInputAndOutputWithHeadersMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*InputAndOutputWithHeadersOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type InputAndOutputWithHeadersInput struct {
	
	HeaderBooleanList []bool
	
	HeaderByte *int8
	
	HeaderDouble *float64
	
	HeaderEnum types.FooEnum
	
	HeaderEnumList []types.FooEnum
	
	HeaderFalseBool *bool
	
	HeaderFloat *float32
	
	HeaderInteger *int32
	
	HeaderIntegerEnum types.IntegerEnum
	
	HeaderIntegerEnumList []types.IntegerEnum
	
	HeaderIntegerList []int32
	
	HeaderLong *int64
	
	HeaderShort *int16
	
	HeaderString *string
	
	HeaderStringList []string
	
	HeaderStringSet []string
	
	HeaderTimestampList []time.Time
	
	HeaderTrueBool *bool
	
	noSmithyDocumentSerde
}

func (v *InputAndOutputWithHeadersInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput)
	serializeBooleanList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerBooleanList, v.HeaderBooleanList)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerByte, v.HeaderByte)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerDouble, v.HeaderDouble)
	s.WriteString(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerEnum, string(v.HeaderEnum))
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerEnumList, v.HeaderEnumList)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerFalseBool, v.HeaderFalseBool)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerFloat, v.HeaderFloat)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerInteger, v.HeaderInteger)
	s.WriteInt32(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerEnum, int32(v.HeaderIntegerEnum))
	serializeIntegerEnumList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerEnumList, v.HeaderIntegerEnumList)
	serializeIntegerList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerList, v.HeaderIntegerList)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerLong, v.HeaderLong)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerShort, v.HeaderShort)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerString, v.HeaderString)
	serializeStringList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerStringList, v.HeaderStringList)
	serializeStringSet(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerStringSet, v.HeaderStringSet)
	serializeTimestampList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerTimestampList, v.HeaderTimestampList)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerTrueBool, v.HeaderTrueBool)
	s.CloseMap()
}
func (v *InputAndOutputWithHeadersInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerBooleanList:
			return deserializeBooleanList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerBooleanList, &v.HeaderBooleanList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerByte:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerByte, &v.HeaderByte)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerDouble:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerDouble, &v.HeaderDouble)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerEnum:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerEnum, &ev); err != nil {
			    return err
			}
			v.HeaderEnum = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerEnumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerEnumList, &v.HeaderEnumList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerFalseBool:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerFalseBool, &v.HeaderFalseBool)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerFloat:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerFloat, &v.HeaderFloat)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerInteger:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerInteger, &v.HeaderInteger)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerEnum:
			var ev int32
			if err := d.ReadInt32(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerEnum, &ev); err != nil {
			    return err
			}
			v.HeaderIntegerEnum = types.IntegerEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerEnumList:
			return deserializeIntegerEnumList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerEnumList, &v.HeaderIntegerEnumList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerList:
			return deserializeIntegerList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerIntegerList, &v.HeaderIntegerList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerLong:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerLong, &v.HeaderLong)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerShort:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerShort, &v.HeaderShort)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerString:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerString, &v.HeaderString)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerStringList:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerStringList, &v.HeaderStringList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerStringSet:
			return deserializeStringSet(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerStringSet, &v.HeaderStringSet)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerTimestampList:
			return deserializeTimestampList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerTimestampList, &v.HeaderTimestampList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerTrueBool:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput_headerTrueBool, &v.HeaderTrueBool)
		}
		return nil
	})
}
type InputAndOutputWithHeadersOutput struct {
	
	HeaderBooleanList []bool
	
	HeaderByte *int8
	
	HeaderDouble *float64
	
	HeaderEnum types.FooEnum
	
	HeaderEnumList []types.FooEnum
	
	HeaderFalseBool *bool
	
	HeaderFloat *float32
	
	HeaderInteger *int32
	
	HeaderIntegerEnum types.IntegerEnum
	
	HeaderIntegerEnumList []types.IntegerEnum
	
	HeaderIntegerList []int32
	
	HeaderLong *int64
	
	HeaderShort *int16
	
	HeaderString *string
	
	HeaderStringList []string
	
	HeaderStringSet []string
	
	HeaderTimestampList []time.Time
	
	HeaderTrueBool *bool
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *InputAndOutputWithHeadersOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput)
	serializeBooleanList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerBooleanList, v.HeaderBooleanList)
	s.WriteInt8Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerByte, v.HeaderByte)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerDouble, v.HeaderDouble)
	s.WriteString(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerEnum, string(v.HeaderEnum))
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerEnumList, v.HeaderEnumList)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerFalseBool, v.HeaderFalseBool)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerFloat, v.HeaderFloat)
	s.WriteInt32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerInteger, v.HeaderInteger)
	s.WriteInt32(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerEnum, int32(v.HeaderIntegerEnum))
	serializeIntegerEnumList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerEnumList, v.HeaderIntegerEnumList)
	serializeIntegerList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerList, v.HeaderIntegerList)
	s.WriteInt64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerLong, v.HeaderLong)
	s.WriteInt16Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerShort, v.HeaderShort)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerString, v.HeaderString)
	serializeStringList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerStringList, v.HeaderStringList)
	serializeStringSet(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerStringSet, v.HeaderStringSet)
	serializeTimestampList(s, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerTimestampList, v.HeaderTimestampList)
	s.WriteBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerTrueBool, v.HeaderTrueBool)
	s.CloseMap()
}
func (v *InputAndOutputWithHeadersOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerBooleanList:
			return deserializeBooleanList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerBooleanList, &v.HeaderBooleanList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerByte:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerByte, &v.HeaderByte)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerDouble:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerDouble, &v.HeaderDouble)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerEnum:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerEnum, &ev); err != nil {
			    return err
			}
			v.HeaderEnum = types.FooEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerEnumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerEnumList, &v.HeaderEnumList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerFalseBool:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerFalseBool, &v.HeaderFalseBool)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerFloat:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerFloat, &v.HeaderFloat)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerInteger:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerInteger, &v.HeaderInteger)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerEnum:
			var ev int32
			if err := d.ReadInt32(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerEnum, &ev); err != nil {
			    return err
			}
			v.HeaderIntegerEnum = types.IntegerEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerEnumList:
			return deserializeIntegerEnumList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerEnumList, &v.HeaderIntegerEnumList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerList:
			return deserializeIntegerList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerIntegerList, &v.HeaderIntegerList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerLong:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerLong, &v.HeaderLong)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerShort:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerShort, &v.HeaderShort)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerString:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerString, &v.HeaderString)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerStringList:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerStringList, &v.HeaderStringList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerStringSet:
			return deserializeStringSet(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerStringSet, &v.HeaderStringSet)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerTimestampList:
			return deserializeTimestampList(d, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerTimestampList, &v.HeaderTimestampList)
			case schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerTrueBool:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput_headerTrueBool, &v.HeaderTrueBool)
		}
		return nil
	})
}
func (c *Client) addOperationInputAndOutputWithHeadersMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.InputAndOutputWithHeaders, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.InputAndOutputWithHeaders, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersInput, schemas.SmithyGoSynthetic_InputAndOutputWithHeadersOutput), output: &InputAndOutputWithHeadersOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "InputAndOutputWithHeaders"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opInputAndOutputWithHeaders(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opInputAndOutputWithHeaders(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "InputAndOutputWithHeaders",
	}
}
