// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This examples adds headers to the input of a request and response by prefix.
func (c *Client) HttpPrefixHeaders(ctx context.Context, params *HttpPrefixHeadersInput, optFns ...func(*Options)) (*HttpPrefixHeadersOutput, error) {
	if params == nil { params = &HttpPrefixHeadersInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "HttpPrefixHeaders", params, optFns, c.addOperationHttpPrefixHeadersMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*HttpPrefixHeadersOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type HttpPrefixHeadersInput struct {
	
	Foo *string
	
	FooMap map[string]string
	
	noSmithyDocumentSerde
}

func (v *HttpPrefixHeadersInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpPrefixHeadersInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_HttpPrefixHeadersInput_foo, v.Foo)
	serializeStringMap(s, schemas.SmithyGoSynthetic_HttpPrefixHeadersInput_fooMap, v.FooMap)
	s.CloseMap()
}
type HttpPrefixHeadersOutput struct {
	
	Foo *string
	
	// Map keys will be normalized to lower-case.
	FooMap map[string]string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *HttpPrefixHeadersOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput_foo, &v.Foo)
			case schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput_fooMap:
			return deserializeStringMap(d, schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput_fooMap, &v.FooMap)
		}
		return nil
	})
}
func (c *Client) addOperationHttpPrefixHeadersMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpPrefixHeaders, schemas.SmithyGoSynthetic_HttpPrefixHeadersInput, schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpPrefixHeaders, schemas.SmithyGoSynthetic_HttpPrefixHeadersInput, schemas.SmithyGoSynthetic_HttpPrefixHeadersOutput), output: &HttpPrefixHeadersOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "HttpPrefixHeaders"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opHttpPrefixHeaders(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opHttpPrefixHeaders(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "HttpPrefixHeaders",
	}
}
