// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) MalformedDouble(ctx context.Context, params *MalformedDoubleInput, optFns ...func(*Options)) (*MalformedDoubleOutput, error) {
	if params == nil { params = &MalformedDoubleInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "MalformedDouble", params, optFns, c.addOperationMalformedDoubleMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*MalformedDoubleOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type MalformedDoubleInput struct {
	
	// This member is required.
	DoubleInPath *float64
	
	DoubleInBody *float64
	
	DoubleInHeader *float64
	
	DoubleInQuery *float64
	
	noSmithyDocumentSerde
}

func (v *MalformedDoubleInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedDoubleInput)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInBody, v.DoubleInBody)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInHeader, v.DoubleInHeader)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInPath, v.DoubleInPath)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInQuery, v.DoubleInQuery)
	s.CloseMap()
}
func (v *MalformedDoubleInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedDoubleInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInBody:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInBody, &v.DoubleInBody)
			case schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInHeader:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInHeader, &v.DoubleInHeader)
			case schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInPath:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInPath, &v.DoubleInPath)
			case schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInQuery:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_MalformedDoubleInput_doubleInQuery, &v.DoubleInQuery)
		}
		return nil
	})
}
type MalformedDoubleOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *MalformedDoubleOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedDoubleOutput)
	s.CloseMap()
}
func (v *MalformedDoubleOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedDoubleOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationMalformedDoubleMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedDouble, schemas.SmithyGoSynthetic_MalformedDoubleInput, schemas.SmithyGoSynthetic_MalformedDoubleOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedDouble, schemas.SmithyGoSynthetic_MalformedDoubleInput, schemas.SmithyGoSynthetic_MalformedDoubleOutput), output: &MalformedDoubleOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "MalformedDouble"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = addOpMalformedDoubleValidationMiddleware(stack); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opMalformedDouble(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opMalformedDouble(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "MalformedDouble",
	}
}
