// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/types"
)

// This example tests sparse map serialization.
func (c *Client) SparseJsonMaps(ctx context.Context, params *SparseJsonMapsInput, optFns ...func(*Options)) (*SparseJsonMapsOutput, error) {
	if params == nil { params = &SparseJsonMapsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "SparseJsonMaps", params, optFns, c.addOperationSparseJsonMapsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*SparseJsonMapsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type SparseJsonMapsInput struct {
	
	SparseBooleanMap map[string]*bool
	
	SparseNumberMap map[string]*int32
	
	SparseSetMap map[string][]string
	
	SparseStringMap map[string]*string
	
	SparseStructMap map[string]*types.GreetingStruct
	
	noSmithyDocumentSerde
}

func (v *SparseJsonMapsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SparseJsonMapsInput)
	serializeSparseBooleanMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseBooleanMap, v.SparseBooleanMap)
	serializeSparseNumberMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseNumberMap, v.SparseNumberMap)
	serializeSparseSetMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseSetMap, v.SparseSetMap)
	serializeSparseStringMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseStringMap, v.SparseStringMap)
	serializeSparseStructMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseStructMap, v.SparseStructMap)
	s.CloseMap()
}
func (v *SparseJsonMapsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SparseJsonMapsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseBooleanMap:
			return deserializeSparseBooleanMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseBooleanMap, &v.SparseBooleanMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseNumberMap:
			return deserializeSparseNumberMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseNumberMap, &v.SparseNumberMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseSetMap:
			return deserializeSparseSetMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseSetMap, &v.SparseSetMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseStringMap:
			return deserializeSparseStringMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseStringMap, &v.SparseStringMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseStructMap:
			return deserializeSparseStructMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsInput_sparseStructMap, &v.SparseStructMap)
		}
		return nil
	})
}
type SparseJsonMapsOutput struct {
	
	SparseBooleanMap map[string]*bool
	
	SparseNumberMap map[string]*int32
	
	SparseSetMap map[string][]string
	
	SparseStringMap map[string]*string
	
	SparseStructMap map[string]*types.GreetingStruct
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *SparseJsonMapsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SparseJsonMapsOutput)
	serializeSparseBooleanMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseBooleanMap, v.SparseBooleanMap)
	serializeSparseNumberMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseNumberMap, v.SparseNumberMap)
	serializeSparseSetMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseSetMap, v.SparseSetMap)
	serializeSparseStringMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseStringMap, v.SparseStringMap)
	serializeSparseStructMap(s, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseStructMap, v.SparseStructMap)
	s.CloseMap()
}
func (v *SparseJsonMapsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SparseJsonMapsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseBooleanMap:
			return deserializeSparseBooleanMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseBooleanMap, &v.SparseBooleanMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseNumberMap:
			return deserializeSparseNumberMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseNumberMap, &v.SparseNumberMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseSetMap:
			return deserializeSparseSetMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseSetMap, &v.SparseSetMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseStringMap:
			return deserializeSparseStringMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseStringMap, &v.SparseStringMap)
			case schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseStructMap:
			return deserializeSparseStructMap(d, schemas.SmithyGoSynthetic_SparseJsonMapsOutput_sparseStructMap, &v.SparseStructMap)
		}
		return nil
	})
}
func (c *Client) addOperationSparseJsonMapsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SparseJsonMaps, schemas.SmithyGoSynthetic_SparseJsonMapsInput, schemas.SmithyGoSynthetic_SparseJsonMapsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SparseJsonMaps, schemas.SmithyGoSynthetic_SparseJsonMapsInput, schemas.SmithyGoSynthetic_SparseJsonMapsOutput), output: &SparseJsonMapsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "SparseJsonMaps"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opSparseJsonMaps(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opSparseJsonMaps(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "SparseJsonMaps",
	}
}
