// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"io"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This examples serializes a streaming media-typed blob shape in the request body.
//
// This examples uses a @mediaType trait on the payload to force a custom
// content-type to be serialized.
func (c *Client) StreamingTraitsWithMediaType(ctx context.Context, params *StreamingTraitsWithMediaTypeInput, optFns ...func(*Options)) (*StreamingTraitsWithMediaTypeOutput, error) {
	if params == nil { params = &StreamingTraitsWithMediaTypeInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "StreamingTraitsWithMediaType", params, optFns, c.addOperationStreamingTraitsWithMediaTypeMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*StreamingTraitsWithMediaTypeOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type StreamingTraitsWithMediaTypeInput struct {
	
	// This value conforms to the media type: text/plain
	Blob io.Reader
	
	Foo *string
	
	noSmithyDocumentSerde
}

func (v *StreamingTraitsWithMediaTypeInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput_foo, v.Foo)
	s.CloseMap()
}
func (v *StreamingTraitsWithMediaTypeInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput_foo, &v.Foo)
		}
		return nil
	})
}
func (v *StreamingTraitsWithMediaTypeInput) GetPayloadStream() io.Reader { return v.Blob }
var _ smithy.StreamingInput = (*StreamingTraitsWithMediaTypeInput)(nil)
func (v *StreamingTraitsWithMediaTypeInput) SetPayloadStream(r io.ReadCloser) { v.Blob = r }
var _ smithy.StreamingOutput = (*StreamingTraitsWithMediaTypeInput)(nil)

type StreamingTraitsWithMediaTypeOutput struct {
	
	// This value conforms to the media type: text/plain
	Blob io.ReadCloser
	
	Foo *string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *StreamingTraitsWithMediaTypeOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput_foo, v.Foo)
	s.CloseMap()
}
func (v *StreamingTraitsWithMediaTypeOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput_foo, &v.Foo)
		}
		return nil
	})
}
func (v *StreamingTraitsWithMediaTypeOutput) GetPayloadStream() io.Reader { return v.Blob }
var _ smithy.StreamingInput = (*StreamingTraitsWithMediaTypeOutput)(nil)
func (v *StreamingTraitsWithMediaTypeOutput) SetPayloadStream(r io.ReadCloser) { v.Blob = r }
var _ smithy.StreamingOutput = (*StreamingTraitsWithMediaTypeOutput)(nil)

func (c *Client) addOperationStreamingTraitsWithMediaTypeMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.StreamingTraitsWithMediaType, schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput, schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.StreamingTraitsWithMediaType, schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeInput, schemas.SmithyGoSynthetic_StreamingTraitsWithMediaTypeOutput), output: &StreamingTraitsWithMediaTypeOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "StreamingTraitsWithMediaType"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opStreamingTraitsWithMediaType(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opStreamingTraitsWithMediaType(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "StreamingTraitsWithMediaType",
	}
}
