// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This example serializes a blob shape in the payload.
//
// In this example, no JSON document is synthesized because the payload is not a
// structure or a union type.
func (c *Client) HttpPayloadTraits(ctx context.Context, params *HttpPayloadTraitsInput, optFns ...func(*Options)) (*HttpPayloadTraitsOutput, error) {
	if params == nil { params = &HttpPayloadTraitsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "HttpPayloadTraits", params, optFns, c.addOperationHttpPayloadTraitsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*HttpPayloadTraitsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type HttpPayloadTraitsInput struct {
	
	Blob []byte
	
	Foo *string
	
	noSmithyDocumentSerde
}

func (v *HttpPayloadTraitsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpPayloadTraitsInput)
	s.WriteBlob(schemas.SmithyGoSynthetic_HttpPayloadTraitsInput_blob, v.Blob)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_HttpPayloadTraitsInput_foo, v.Foo)
	s.CloseMap()
}
func (v *HttpPayloadTraitsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpPayloadTraitsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpPayloadTraitsInput_blob:
			return d.ReadBlob(schemas.SmithyGoSynthetic_HttpPayloadTraitsInput_blob, &v.Blob)
			case schemas.SmithyGoSynthetic_HttpPayloadTraitsInput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_HttpPayloadTraitsInput_foo, &v.Foo)
		}
		return nil
	})
}
type HttpPayloadTraitsOutput struct {
	
	Blob []byte
	
	Foo *string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *HttpPayloadTraitsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput)
	s.WriteBlob(schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput_blob, v.Blob)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput_foo, v.Foo)
	s.CloseMap()
}
func (v *HttpPayloadTraitsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput_blob:
			return d.ReadBlob(schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput_blob, &v.Blob)
			case schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput_foo:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput_foo, &v.Foo)
		}
		return nil
	})
}
func (c *Client) addOperationHttpPayloadTraitsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpPayloadTraits, schemas.SmithyGoSynthetic_HttpPayloadTraitsInput, schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpPayloadTraits, schemas.SmithyGoSynthetic_HttpPayloadTraitsInput, schemas.SmithyGoSynthetic_HttpPayloadTraitsOutput), output: &HttpPayloadTraitsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "HttpPayloadTraits"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opHttpPayloadTraits(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opHttpPayloadTraits(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "HttpPayloadTraits",
	}
}
