// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
)

func (c *Client) MalformedTimestampPathHttpDate(ctx context.Context, params *MalformedTimestampPathHttpDateInput, optFns ...func(*Options)) (*MalformedTimestampPathHttpDateOutput, error) {
	if params == nil { params = &MalformedTimestampPathHttpDateInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "MalformedTimestampPathHttpDate", params, optFns, c.addOperationMalformedTimestampPathHttpDateMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*MalformedTimestampPathHttpDateOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type MalformedTimestampPathHttpDateInput struct {
	
	// This member is required.
	Timestamp *time.Time
	
	noSmithyDocumentSerde
}

func (v *MalformedTimestampPathHttpDateInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput_timestamp, v.Timestamp)
	s.CloseMap()
}
func (v *MalformedTimestampPathHttpDateInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput_timestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput_timestamp, &v.Timestamp)
		}
		return nil
	})
}
type MalformedTimestampPathHttpDateOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *MalformedTimestampPathHttpDateOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateOutput)
	s.CloseMap()
}
func (v *MalformedTimestampPathHttpDateOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationMalformedTimestampPathHttpDateMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedTimestampPathHttpDate, schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput, schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedTimestampPathHttpDate, schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateInput, schemas.SmithyGoSynthetic_MalformedTimestampPathHttpDateOutput), output: &MalformedTimestampPathHttpDateOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "MalformedTimestampPathHttpDate"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = addOpMalformedTimestampPathHttpDateValidationMiddleware(stack); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opMalformedTimestampPathHttpDate(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opMalformedTimestampPathHttpDate(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "MalformedTimestampPathHttpDate",
	}
}
