// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"io"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// This examples serializes a streaming blob shape with a required content length
// in the request body.
//
// In this example, no JSON document is synthesized because the payload is not a
// structure or a union type.
func (c *Client) StreamingTraitsRequireLength(ctx context.Context, params *StreamingTraitsRequireLengthInput, optFns ...func(*Options)) (*StreamingTraitsRequireLengthOutput, error) {
	if params == nil { params = &StreamingTraitsRequireLengthInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "StreamingTraitsRequireLength", params, optFns, c.addOperationStreamingTraitsRequireLengthMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*StreamingTraitsRequireLengthOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type StreamingTraitsRequireLengthInput struct {
	
	Blob io.Reader
	
	Foo *string
	
	noSmithyDocumentSerde
}

func (v *StreamingTraitsRequireLengthInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthInput_foo, v.Foo)
	s.CloseMap()
}
func (v *StreamingTraitsRequireLengthInput) GetPayloadStream() io.Reader { return v.Blob }
var _ smithy.StreamingInput = (*StreamingTraitsRequireLengthInput)(nil)
func (v *StreamingTraitsRequireLengthInput) SetPayloadStream(r io.ReadCloser) { v.Blob = r }
var _ smithy.StreamingOutput = (*StreamingTraitsRequireLengthInput)(nil)

type StreamingTraitsRequireLengthOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *StreamingTraitsRequireLengthOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthOutput)
	s.CloseMap()
}
func (v *StreamingTraitsRequireLengthOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationStreamingTraitsRequireLengthMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.StreamingTraitsRequireLength, schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthInput, schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.StreamingTraitsRequireLength, schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthInput, schemas.SmithyGoSynthetic_StreamingTraitsRequireLengthOutput), output: &StreamingTraitsRequireLengthOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "StreamingTraitsRequireLength"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opStreamingTraitsRequireLength(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opStreamingTraitsRequireLength(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "StreamingTraitsRequireLength",
	}
}
