// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/types"
)

// Omits serializing empty lists. Because empty strings are serilized as Foo= ,
// empty lists cannot also be serialized as Foo= and instead must be omitted.
func (c *Client) OmitsSerializingEmptyLists(ctx context.Context, params *OmitsSerializingEmptyListsInput, optFns ...func(*Options)) (*OmitsSerializingEmptyListsOutput, error) {
	if params == nil { params = &OmitsSerializingEmptyListsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "OmitsSerializingEmptyLists", params, optFns, c.addOperationOmitsSerializingEmptyListsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*OmitsSerializingEmptyListsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type OmitsSerializingEmptyListsInput struct {
	
	QueryBooleanList []bool
	
	QueryDoubleList []float64
	
	QueryEnumList []types.FooEnum
	
	QueryIntegerEnumList []types.IntegerEnum
	
	QueryIntegerList []int32
	
	QueryStringList []string
	
	QueryTimestampList []time.Time
	
	noSmithyDocumentSerde
}

func (v *OmitsSerializingEmptyListsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput)
	serializeBooleanList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryBooleanList, v.QueryBooleanList)
	serializeDoubleList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryDoubleList, v.QueryDoubleList)
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryEnumList, v.QueryEnumList)
	serializeIntegerEnumList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryIntegerEnumList, v.QueryIntegerEnumList)
	serializeIntegerList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryIntegerList, v.QueryIntegerList)
	serializeStringList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryStringList, v.QueryStringList)
	serializeTimestampList(s, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryTimestampList, v.QueryTimestampList)
	s.CloseMap()
}
func (v *OmitsSerializingEmptyListsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryBooleanList:
			return deserializeBooleanList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryBooleanList, &v.QueryBooleanList)
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryDoubleList:
			return deserializeDoubleList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryDoubleList, &v.QueryDoubleList)
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryEnumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryEnumList, &v.QueryEnumList)
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryIntegerEnumList:
			return deserializeIntegerEnumList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryIntegerEnumList, &v.QueryIntegerEnumList)
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryIntegerList:
			return deserializeIntegerList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryIntegerList, &v.QueryIntegerList)
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryStringList:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryStringList, &v.QueryStringList)
			case schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryTimestampList:
			return deserializeTimestampList(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput_queryTimestampList, &v.QueryTimestampList)
		}
		return nil
	})
}
type OmitsSerializingEmptyListsOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *OmitsSerializingEmptyListsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsOutput)
	s.CloseMap()
}
func (v *OmitsSerializingEmptyListsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationOmitsSerializingEmptyListsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OmitsSerializingEmptyLists, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OmitsSerializingEmptyLists, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsInput, schemas.SmithyGoSynthetic_OmitsSerializingEmptyListsOutput), output: &OmitsSerializingEmptyListsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "OmitsSerializingEmptyLists"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opOmitsSerializingEmptyLists(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opOmitsSerializingEmptyLists(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "OmitsSerializingEmptyLists",
	}
}
