// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) MalformedContentTypeWithPayload(ctx context.Context, params *MalformedContentTypeWithPayloadInput, optFns ...func(*Options)) (*MalformedContentTypeWithPayloadOutput, error) {
	if params == nil { params = &MalformedContentTypeWithPayloadInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "MalformedContentTypeWithPayload", params, optFns, c.addOperationMalformedContentTypeWithPayloadMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*MalformedContentTypeWithPayloadOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type MalformedContentTypeWithPayloadInput struct {
	
	// This value conforms to the media type: image/jpeg
	Payload []byte
	
	noSmithyDocumentSerde
}

func (v *MalformedContentTypeWithPayloadInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput)
	s.WriteBlob(schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput_payload, v.Payload)
	s.CloseMap()
}
func (v *MalformedContentTypeWithPayloadInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput_payload:
			return d.ReadBlob(schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput_payload, &v.Payload)
		}
		return nil
	})
}
type MalformedContentTypeWithPayloadOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *MalformedContentTypeWithPayloadOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadOutput)
	s.CloseMap()
}
func (v *MalformedContentTypeWithPayloadOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationMalformedContentTypeWithPayloadMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedContentTypeWithPayload, schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput, schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.MalformedContentTypeWithPayload, schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadInput, schemas.SmithyGoSynthetic_MalformedContentTypeWithPayloadOutput), output: &MalformedContentTypeWithPayloadOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "MalformedContentTypeWithPayload"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opMalformedContentTypeWithPayload(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opMalformedContentTypeWithPayload(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "MalformedContentTypeWithPayload",
	}
}
