// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/types"
)

func (c *Client) HttpEnumPayload(ctx context.Context, params *HttpEnumPayloadInput, optFns ...func(*Options)) (*HttpEnumPayloadOutput, error) {
	if params == nil { params = &HttpEnumPayloadInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "HttpEnumPayload", params, optFns, c.addOperationHttpEnumPayloadMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*HttpEnumPayloadOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type HttpEnumPayloadInput struct {
	
	Payload types.StringEnum
	
	noSmithyDocumentSerde
}

func (v *HttpEnumPayloadInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpEnumPayloadInput)
	s.WriteString(schemas.SmithyGoSynthetic_HttpEnumPayloadInput_payload, string(v.Payload))
	s.CloseMap()
}
func (v *HttpEnumPayloadInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpEnumPayloadInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpEnumPayloadInput_payload:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_HttpEnumPayloadInput_payload, &ev); err != nil {
			    return err
			}
			v.Payload = types.StringEnum(ev)
			return nil
		}
		return nil
	})
}
type HttpEnumPayloadOutput struct {
	
	Payload types.StringEnum
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *HttpEnumPayloadOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpEnumPayloadOutput)
	s.WriteString(schemas.SmithyGoSynthetic_HttpEnumPayloadOutput_payload, string(v.Payload))
	s.CloseMap()
}
func (v *HttpEnumPayloadOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpEnumPayloadOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpEnumPayloadOutput_payload:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_HttpEnumPayloadOutput_payload, &ev); err != nil {
			    return err
			}
			v.Payload = types.StringEnum(ev)
			return nil
		}
		return nil
	})
}
func (c *Client) addOperationHttpEnumPayloadMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpEnumPayload, schemas.SmithyGoSynthetic_HttpEnumPayloadInput, schemas.SmithyGoSynthetic_HttpEnumPayloadOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpEnumPayload, schemas.SmithyGoSynthetic_HttpEnumPayloadInput, schemas.SmithyGoSynthetic_HttpEnumPayloadOutput), output: &HttpEnumPayloadOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "HttpEnumPayload"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opHttpEnumPayload(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opHttpEnumPayload(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "HttpEnumPayload",
	}
}
