// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

// Omits null, but serializes empty string value.
func (c *Client) OmitsNullSerializesEmptyString(ctx context.Context, params *OmitsNullSerializesEmptyStringInput, optFns ...func(*Options)) (*OmitsNullSerializesEmptyStringOutput, error) {
	if params == nil { params = &OmitsNullSerializesEmptyStringInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "OmitsNullSerializesEmptyString", params, optFns, c.addOperationOmitsNullSerializesEmptyStringMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*OmitsNullSerializesEmptyStringOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type OmitsNullSerializesEmptyStringInput struct {
	
	EmptyString *string
	
	NullValue *string
	
	noSmithyDocumentSerde
}

func (v *OmitsNullSerializesEmptyStringInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput_emptyString, v.EmptyString)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput_nullValue, v.NullValue)
	s.CloseMap()
}
func (v *OmitsNullSerializesEmptyStringInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput_emptyString:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput_emptyString, &v.EmptyString)
			case schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput_nullValue:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput_nullValue, &v.NullValue)
		}
		return nil
	})
}
type OmitsNullSerializesEmptyStringOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *OmitsNullSerializesEmptyStringOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringOutput)
	s.CloseMap()
}
func (v *OmitsNullSerializesEmptyStringOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationOmitsNullSerializesEmptyStringMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OmitsNullSerializesEmptyString, schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput, schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OmitsNullSerializesEmptyString, schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringInput, schemas.SmithyGoSynthetic_OmitsNullSerializesEmptyStringOutput), output: &OmitsNullSerializesEmptyStringOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "OmitsNullSerializesEmptyString"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opOmitsNullSerializesEmptyString(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opOmitsNullSerializesEmptyString(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "OmitsNullSerializesEmptyString",
	}
}
