// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) HttpRequestWithFloatLabels(ctx context.Context, params *HttpRequestWithFloatLabelsInput, optFns ...func(*Options)) (*HttpRequestWithFloatLabelsOutput, error) {
	if params == nil { params = &HttpRequestWithFloatLabelsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "HttpRequestWithFloatLabels", params, optFns, c.addOperationHttpRequestWithFloatLabelsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*HttpRequestWithFloatLabelsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type HttpRequestWithFloatLabelsInput struct {
	
	// This member is required.
	Double *float64
	
	// This member is required.
	Float *float32
	
	noSmithyDocumentSerde
}

func (v *HttpRequestWithFloatLabelsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput)
	s.WriteFloat64Ptr(schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput_double, v.Double)
	s.WriteFloat32Ptr(schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput_float, v.Float)
	s.CloseMap()
}
func (v *HttpRequestWithFloatLabelsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput_double:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput_double, &v.Double)
			case schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput_float:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput_float, &v.Float)
		}
		return nil
	})
}
type HttpRequestWithFloatLabelsOutput struct {
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *HttpRequestWithFloatLabelsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsOutput)
	s.CloseMap()
}
func (v *HttpRequestWithFloatLabelsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsOutput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
func (c *Client) addOperationHttpRequestWithFloatLabelsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpRequestWithFloatLabels, schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput, schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.HttpRequestWithFloatLabels, schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsInput, schemas.SmithyGoSynthetic_HttpRequestWithFloatLabelsOutput), output: &HttpRequestWithFloatLabelsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "HttpRequestWithFloatLabels"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = addOpHttpRequestWithFloatLabelsValidationMiddleware(stack); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opHttpRequestWithFloatLabels(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opHttpRequestWithFloatLabels(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "HttpRequestWithFloatLabels",
	}
}
