// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
)

func (c *Client) FractionalSeconds(ctx context.Context, params *FractionalSecondsInput, optFns ...func(*Options)) (*FractionalSecondsOutput, error) {
	if params == nil { params = &FractionalSecondsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "FractionalSeconds", params, optFns, c.addOperationFractionalSecondsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*FractionalSecondsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type FractionalSecondsInput struct {
	
	noSmithyDocumentSerde
}

func (v *FractionalSecondsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_FractionalSecondsInput)
	s.CloseMap()
}
func (v *FractionalSecondsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_FractionalSecondsInput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
type FractionalSecondsOutput struct {
	
	Datetime *time.Time
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *FractionalSecondsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_FractionalSecondsOutput)
	s.WriteTimePtr(schemas.SmithyGoSynthetic_FractionalSecondsOutput_datetime, v.Datetime)
	s.CloseMap()
}
func (v *FractionalSecondsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_FractionalSecondsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_FractionalSecondsOutput_datetime:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_FractionalSecondsOutput_datetime, &v.Datetime)
		}
		return nil
	})
}
func (c *Client) addOperationFractionalSecondsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.FractionalSeconds, schemas.SmithyGoSynthetic_FractionalSecondsInput, schemas.SmithyGoSynthetic_FractionalSecondsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.FractionalSeconds, schemas.SmithyGoSynthetic_FractionalSecondsInput, schemas.SmithyGoSynthetic_FractionalSecondsOutput), output: &FractionalSecondsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "FractionalSeconds"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opFractionalSeconds(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opFractionalSeconds(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "FractionalSeconds",
	}
}
