// Code generated by smithy-go-codegen DO NOT EDIT.


package awsrestjson

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/awsrestjson/types"
)

// The example tests basic map serialization.
func (c *Client) JsonMaps(ctx context.Context, params *JsonMapsInput, optFns ...func(*Options)) (*JsonMapsOutput, error) {
	if params == nil { params = &JsonMapsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "JsonMaps", params, optFns, c.addOperationJsonMapsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*JsonMapsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type JsonMapsInput struct {
	
	DenseBooleanMap map[string]bool
	
	DenseNumberMap map[string]int32
	
	DenseSetMap map[string][]string
	
	DenseStringMap map[string]string
	
	DenseStructMap map[string]types.GreetingStruct
	
	noSmithyDocumentSerde
}

func (v *JsonMapsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_JsonMapsInput)
	serializeDenseBooleanMap(s, schemas.SmithyGoSynthetic_JsonMapsInput_denseBooleanMap, v.DenseBooleanMap)
	serializeDenseNumberMap(s, schemas.SmithyGoSynthetic_JsonMapsInput_denseNumberMap, v.DenseNumberMap)
	serializeDenseSetMap(s, schemas.SmithyGoSynthetic_JsonMapsInput_denseSetMap, v.DenseSetMap)
	serializeDenseStringMap(s, schemas.SmithyGoSynthetic_JsonMapsInput_denseStringMap, v.DenseStringMap)
	serializeDenseStructMap(s, schemas.SmithyGoSynthetic_JsonMapsInput_denseStructMap, v.DenseStructMap)
	s.CloseMap()
}
func (v *JsonMapsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_JsonMapsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_JsonMapsInput_denseBooleanMap:
			return deserializeDenseBooleanMap(d, schemas.SmithyGoSynthetic_JsonMapsInput_denseBooleanMap, &v.DenseBooleanMap)
			case schemas.SmithyGoSynthetic_JsonMapsInput_denseNumberMap:
			return deserializeDenseNumberMap(d, schemas.SmithyGoSynthetic_JsonMapsInput_denseNumberMap, &v.DenseNumberMap)
			case schemas.SmithyGoSynthetic_JsonMapsInput_denseSetMap:
			return deserializeDenseSetMap(d, schemas.SmithyGoSynthetic_JsonMapsInput_denseSetMap, &v.DenseSetMap)
			case schemas.SmithyGoSynthetic_JsonMapsInput_denseStringMap:
			return deserializeDenseStringMap(d, schemas.SmithyGoSynthetic_JsonMapsInput_denseStringMap, &v.DenseStringMap)
			case schemas.SmithyGoSynthetic_JsonMapsInput_denseStructMap:
			return deserializeDenseStructMap(d, schemas.SmithyGoSynthetic_JsonMapsInput_denseStructMap, &v.DenseStructMap)
		}
		return nil
	})
}
type JsonMapsOutput struct {
	
	DenseBooleanMap map[string]bool
	
	DenseNumberMap map[string]int32
	
	DenseSetMap map[string][]string
	
	DenseStringMap map[string]string
	
	DenseStructMap map[string]types.GreetingStruct
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *JsonMapsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_JsonMapsOutput)
	serializeDenseBooleanMap(s, schemas.SmithyGoSynthetic_JsonMapsOutput_denseBooleanMap, v.DenseBooleanMap)
	serializeDenseNumberMap(s, schemas.SmithyGoSynthetic_JsonMapsOutput_denseNumberMap, v.DenseNumberMap)
	serializeDenseSetMap(s, schemas.SmithyGoSynthetic_JsonMapsOutput_denseSetMap, v.DenseSetMap)
	serializeDenseStringMap(s, schemas.SmithyGoSynthetic_JsonMapsOutput_denseStringMap, v.DenseStringMap)
	serializeDenseStructMap(s, schemas.SmithyGoSynthetic_JsonMapsOutput_denseStructMap, v.DenseStructMap)
	s.CloseMap()
}
func (v *JsonMapsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_JsonMapsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_JsonMapsOutput_denseBooleanMap:
			return deserializeDenseBooleanMap(d, schemas.SmithyGoSynthetic_JsonMapsOutput_denseBooleanMap, &v.DenseBooleanMap)
			case schemas.SmithyGoSynthetic_JsonMapsOutput_denseNumberMap:
			return deserializeDenseNumberMap(d, schemas.SmithyGoSynthetic_JsonMapsOutput_denseNumberMap, &v.DenseNumberMap)
			case schemas.SmithyGoSynthetic_JsonMapsOutput_denseSetMap:
			return deserializeDenseSetMap(d, schemas.SmithyGoSynthetic_JsonMapsOutput_denseSetMap, &v.DenseSetMap)
			case schemas.SmithyGoSynthetic_JsonMapsOutput_denseStringMap:
			return deserializeDenseStringMap(d, schemas.SmithyGoSynthetic_JsonMapsOutput_denseStringMap, &v.DenseStringMap)
			case schemas.SmithyGoSynthetic_JsonMapsOutput_denseStructMap:
			return deserializeDenseStructMap(d, schemas.SmithyGoSynthetic_JsonMapsOutput_denseStructMap, &v.DenseStructMap)
		}
		return nil
	})
}
func (c *Client) addOperationJsonMapsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.JsonMaps, schemas.SmithyGoSynthetic_JsonMapsInput, schemas.SmithyGoSynthetic_JsonMapsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.JsonMaps, schemas.SmithyGoSynthetic_JsonMapsInput, schemas.SmithyGoSynthetic_JsonMapsOutput), output: &JsonMapsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "JsonMaps"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opJsonMaps(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opJsonMaps(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "JsonMaps",
	}
}
