// Code generated by smithy-go-codegen DO NOT EDIT.


package smithyrpcv2cbor

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) SparseNullsOperation(ctx context.Context, params *SparseNullsOperationInput, optFns ...func(*Options)) (*SparseNullsOperationOutput, error) {
	if params == nil { params = &SparseNullsOperationInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "SparseNullsOperation", params, optFns, c.addOperationSparseNullsOperationMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*SparseNullsOperationOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type SparseNullsOperationInput struct {
	
	SparseStringList []*string
	
	SparseStringMap map[string]*string
	
	noSmithyDocumentSerde
}

func (v *SparseNullsOperationInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SparseNullsOperationInput)
	serializeSparseStringList(s, schemas.SmithyGoSynthetic_SparseNullsOperationInput_sparseStringList, v.SparseStringList)
	serializeSparseStringMap(s, schemas.SmithyGoSynthetic_SparseNullsOperationInput_sparseStringMap, v.SparseStringMap)
	s.CloseMap()
}
func (v *SparseNullsOperationInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SparseNullsOperationInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SparseNullsOperationInput_sparseStringList:
			return deserializeSparseStringList(d, schemas.SmithyGoSynthetic_SparseNullsOperationInput_sparseStringList, &v.SparseStringList)
			case schemas.SmithyGoSynthetic_SparseNullsOperationInput_sparseStringMap:
			return deserializeSparseStringMap(d, schemas.SmithyGoSynthetic_SparseNullsOperationInput_sparseStringMap, &v.SparseStringMap)
		}
		return nil
	})
}
type SparseNullsOperationOutput struct {
	
	SparseStringList []*string
	
	SparseStringMap map[string]*string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *SparseNullsOperationOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_SparseNullsOperationOutput)
	serializeSparseStringList(s, schemas.SmithyGoSynthetic_SparseNullsOperationOutput_sparseStringList, v.SparseStringList)
	serializeSparseStringMap(s, schemas.SmithyGoSynthetic_SparseNullsOperationOutput_sparseStringMap, v.SparseStringMap)
	s.CloseMap()
}
func (v *SparseNullsOperationOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_SparseNullsOperationOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_SparseNullsOperationOutput_sparseStringList:
			return deserializeSparseStringList(d, schemas.SmithyGoSynthetic_SparseNullsOperationOutput_sparseStringList, &v.SparseStringList)
			case schemas.SmithyGoSynthetic_SparseNullsOperationOutput_sparseStringMap:
			return deserializeSparseStringMap(d, schemas.SmithyGoSynthetic_SparseNullsOperationOutput_sparseStringMap, &v.SparseStringMap)
		}
		return nil
	})
}
func (c *Client) addOperationSparseNullsOperationMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SparseNullsOperation, schemas.SmithyGoSynthetic_SparseNullsOperationInput, schemas.SmithyGoSynthetic_SparseNullsOperationOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.SparseNullsOperation, schemas.SmithyGoSynthetic_SparseNullsOperationInput, schemas.SmithyGoSynthetic_SparseNullsOperationOutput), output: &SparseNullsOperationOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "SparseNullsOperation"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addUserAgentFeatureProtocolRPCV2CBOR(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opSparseNullsOperation(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opSparseNullsOperation(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "SparseNullsOperation",
	}
}
