// Code generated by smithy-go-codegen DO NOT EDIT.


package smithyrpcv2cbor

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/types"
)

func (c *Client) RpcV2CborSparseMaps(ctx context.Context, params *RpcV2CborSparseMapsInput, optFns ...func(*Options)) (*RpcV2CborSparseMapsOutput, error) {
	if params == nil { params = &RpcV2CborSparseMapsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "RpcV2CborSparseMaps", params, optFns, c.addOperationRpcV2CborSparseMapsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*RpcV2CborSparseMapsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type RpcV2CborSparseMapsInput struct {
	
	SparseBooleanMap map[string]*bool
	
	SparseNumberMap map[string]*int32
	
	SparseSetMap map[string][]string
	
	SparseStringMap map[string]*string
	
	SparseStructMap map[string]*types.GreetingStruct
	
	noSmithyDocumentSerde
}

func (v *RpcV2CborSparseMapsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput)
	serializeSparseBooleanMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseBooleanMap, v.SparseBooleanMap)
	serializeSparseNumberMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseNumberMap, v.SparseNumberMap)
	serializeSparseSetMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseSetMap, v.SparseSetMap)
	serializeSparseStringMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseStringMap, v.SparseStringMap)
	serializeSparseStructMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseStructMap, v.SparseStructMap)
	s.CloseMap()
}
func (v *RpcV2CborSparseMapsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseBooleanMap:
			return deserializeSparseBooleanMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseBooleanMap, &v.SparseBooleanMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseNumberMap:
			return deserializeSparseNumberMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseNumberMap, &v.SparseNumberMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseSetMap:
			return deserializeSparseSetMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseSetMap, &v.SparseSetMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseStringMap:
			return deserializeSparseStringMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseStringMap, &v.SparseStringMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseStructMap:
			return deserializeSparseStructMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput_sparseStructMap, &v.SparseStructMap)
		}
		return nil
	})
}
type RpcV2CborSparseMapsOutput struct {
	
	SparseBooleanMap map[string]*bool
	
	SparseNumberMap map[string]*int32
	
	SparseSetMap map[string][]string
	
	SparseStringMap map[string]*string
	
	SparseStructMap map[string]*types.GreetingStruct
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *RpcV2CborSparseMapsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput)
	serializeSparseBooleanMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseBooleanMap, v.SparseBooleanMap)
	serializeSparseNumberMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseNumberMap, v.SparseNumberMap)
	serializeSparseSetMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseSetMap, v.SparseSetMap)
	serializeSparseStringMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseStringMap, v.SparseStringMap)
	serializeSparseStructMap(s, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseStructMap, v.SparseStructMap)
	s.CloseMap()
}
func (v *RpcV2CborSparseMapsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseBooleanMap:
			return deserializeSparseBooleanMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseBooleanMap, &v.SparseBooleanMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseNumberMap:
			return deserializeSparseNumberMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseNumberMap, &v.SparseNumberMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseSetMap:
			return deserializeSparseSetMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseSetMap, &v.SparseSetMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseStringMap:
			return deserializeSparseStringMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseStringMap, &v.SparseStringMap)
			case schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseStructMap:
			return deserializeSparseStructMap(d, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput_sparseStructMap, &v.SparseStructMap)
		}
		return nil
	})
}
func (c *Client) addOperationRpcV2CborSparseMapsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.RpcV2CborSparseMaps, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.RpcV2CborSparseMaps, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsInput, schemas.SmithyGoSynthetic_RpcV2CborSparseMapsOutput), output: &RpcV2CborSparseMapsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "RpcV2CborSparseMaps"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addUserAgentFeatureProtocolRPCV2CBOR(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opRpcV2CborSparseMaps(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opRpcV2CborSparseMaps(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "RpcV2CborSparseMaps",
	}
}
