// Code generated by smithy-go-codegen DO NOT EDIT.


package smithyrpcv2cbor

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/types"
)

// This test case serializes JSON lists for the following cases for both input and
// output:
//
//   - Normal lists.
//   - Normal sets.
//   - Lists of lists.
//   - Lists of structures.
func (c *Client) RpcV2CborLists(ctx context.Context, params *RpcV2CborListsInput, optFns ...func(*Options)) (*RpcV2CborListsOutput, error) {
	if params == nil { params = &RpcV2CborListsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "RpcV2CborLists", params, optFns, c.addOperationRpcV2CborListsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*RpcV2CborListsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type RpcV2CborListsInput struct {
	
	BlobList [][]byte
	
	BooleanList []bool
	
	EnumList []types.FooEnum
	
	IntEnumList []types.IntegerEnum
	
	IntegerList []int32
	
	// A list of lists of strings.
	NestedStringList [][]string
	
	StringList []string
	
	StringSet []string
	
	StructureList []types.StructureListMember
	
	TimestampList []time.Time
	
	noSmithyDocumentSerde
}

func (v *RpcV2CborListsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_RpcV2CborListsInput)
	serializeBlobList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_blobList, v.BlobList)
	serializeBooleanList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_booleanList, v.BooleanList)
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_enumList, v.EnumList)
	serializeIntegerEnumList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_intEnumList, v.IntEnumList)
	serializeIntegerList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_integerList, v.IntegerList)
	serializeNestedStringList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_nestedStringList, v.NestedStringList)
	serializeStringList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_stringList, v.StringList)
	serializeStringSet(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_stringSet, v.StringSet)
	serializeStructureList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_structureList, v.StructureList)
	serializeTimestampList(s, schemas.SmithyGoSynthetic_RpcV2CborListsInput_timestampList, v.TimestampList)
	s.CloseMap()
}
func (v *RpcV2CborListsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_blobList:
			return deserializeBlobList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_blobList, &v.BlobList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_booleanList:
			return deserializeBooleanList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_booleanList, &v.BooleanList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_enumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_enumList, &v.EnumList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_intEnumList:
			return deserializeIntegerEnumList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_intEnumList, &v.IntEnumList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_integerList:
			return deserializeIntegerList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_integerList, &v.IntegerList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_nestedStringList:
			return deserializeNestedStringList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_nestedStringList, &v.NestedStringList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_stringList:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_stringList, &v.StringList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_stringSet:
			return deserializeStringSet(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_stringSet, &v.StringSet)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_structureList:
			return deserializeStructureList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_structureList, &v.StructureList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsInput_timestampList:
			return deserializeTimestampList(d, schemas.SmithyGoSynthetic_RpcV2CborListsInput_timestampList, &v.TimestampList)
		}
		return nil
	})
}
type RpcV2CborListsOutput struct {
	
	BlobList [][]byte
	
	BooleanList []bool
	
	EnumList []types.FooEnum
	
	IntEnumList []types.IntegerEnum
	
	IntegerList []int32
	
	// A list of lists of strings.
	NestedStringList [][]string
	
	StringList []string
	
	StringSet []string
	
	StructureList []types.StructureListMember
	
	TimestampList []time.Time
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *RpcV2CborListsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_RpcV2CborListsOutput)
	serializeBlobList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_blobList, v.BlobList)
	serializeBooleanList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_booleanList, v.BooleanList)
	serializeFooEnumList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_enumList, v.EnumList)
	serializeIntegerEnumList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_intEnumList, v.IntEnumList)
	serializeIntegerList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_integerList, v.IntegerList)
	serializeNestedStringList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_nestedStringList, v.NestedStringList)
	serializeStringList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_stringList, v.StringList)
	serializeStringSet(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_stringSet, v.StringSet)
	serializeStructureList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_structureList, v.StructureList)
	serializeTimestampList(s, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_timestampList, v.TimestampList)
	s.CloseMap()
}
func (v *RpcV2CborListsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_blobList:
			return deserializeBlobList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_blobList, &v.BlobList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_booleanList:
			return deserializeBooleanList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_booleanList, &v.BooleanList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_enumList:
			return deserializeFooEnumList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_enumList, &v.EnumList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_intEnumList:
			return deserializeIntegerEnumList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_intEnumList, &v.IntEnumList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_integerList:
			return deserializeIntegerList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_integerList, &v.IntegerList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_nestedStringList:
			return deserializeNestedStringList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_nestedStringList, &v.NestedStringList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_stringList:
			return deserializeStringList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_stringList, &v.StringList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_stringSet:
			return deserializeStringSet(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_stringSet, &v.StringSet)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_structureList:
			return deserializeStructureList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_structureList, &v.StructureList)
			case schemas.SmithyGoSynthetic_RpcV2CborListsOutput_timestampList:
			return deserializeTimestampList(d, schemas.SmithyGoSynthetic_RpcV2CborListsOutput_timestampList, &v.TimestampList)
		}
		return nil
	})
}
func (c *Client) addOperationRpcV2CborListsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.RpcV2CborLists, schemas.SmithyGoSynthetic_RpcV2CborListsInput, schemas.SmithyGoSynthetic_RpcV2CborListsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.RpcV2CborLists, schemas.SmithyGoSynthetic_RpcV2CborListsInput, schemas.SmithyGoSynthetic_RpcV2CborListsOutput), output: &RpcV2CborListsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "RpcV2CborLists"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addUserAgentFeatureProtocolRPCV2CBOR(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opRpcV2CborLists(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opRpcV2CborLists(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "RpcV2CborLists",
	}
}
