// Code generated by smithy-go-codegen DO NOT EDIT.


package smithyrpcv2cbor

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/types"
)

// The example tests basic map serialization.
func (c *Client) RpcV2CborDenseMaps(ctx context.Context, params *RpcV2CborDenseMapsInput, optFns ...func(*Options)) (*RpcV2CborDenseMapsOutput, error) {
	if params == nil { params = &RpcV2CborDenseMapsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "RpcV2CborDenseMaps", params, optFns, c.addOperationRpcV2CborDenseMapsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*RpcV2CborDenseMapsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type RpcV2CborDenseMapsInput struct {
	
	DenseBooleanMap map[string]bool
	
	DenseNumberMap map[string]int32
	
	DenseSetMap map[string][]string
	
	DenseStringMap map[string]string
	
	DenseStructMap map[string]types.GreetingStruct
	
	noSmithyDocumentSerde
}

func (v *RpcV2CborDenseMapsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput)
	serializeDenseBooleanMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseBooleanMap, v.DenseBooleanMap)
	serializeDenseNumberMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseNumberMap, v.DenseNumberMap)
	serializeDenseSetMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseSetMap, v.DenseSetMap)
	serializeDenseStringMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseStringMap, v.DenseStringMap)
	serializeDenseStructMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseStructMap, v.DenseStructMap)
	s.CloseMap()
}
func (v *RpcV2CborDenseMapsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseBooleanMap:
			return deserializeDenseBooleanMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseBooleanMap, &v.DenseBooleanMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseNumberMap:
			return deserializeDenseNumberMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseNumberMap, &v.DenseNumberMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseSetMap:
			return deserializeDenseSetMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseSetMap, &v.DenseSetMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseStringMap:
			return deserializeDenseStringMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseStringMap, &v.DenseStringMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseStructMap:
			return deserializeDenseStructMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput_denseStructMap, &v.DenseStructMap)
		}
		return nil
	})
}
type RpcV2CborDenseMapsOutput struct {
	
	DenseBooleanMap map[string]bool
	
	DenseNumberMap map[string]int32
	
	DenseSetMap map[string][]string
	
	DenseStringMap map[string]string
	
	DenseStructMap map[string]types.GreetingStruct
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *RpcV2CborDenseMapsOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput)
	serializeDenseBooleanMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseBooleanMap, v.DenseBooleanMap)
	serializeDenseNumberMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseNumberMap, v.DenseNumberMap)
	serializeDenseSetMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseSetMap, v.DenseSetMap)
	serializeDenseStringMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseStringMap, v.DenseStringMap)
	serializeDenseStructMap(s, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseStructMap, v.DenseStructMap)
	s.CloseMap()
}
func (v *RpcV2CborDenseMapsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseBooleanMap:
			return deserializeDenseBooleanMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseBooleanMap, &v.DenseBooleanMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseNumberMap:
			return deserializeDenseNumberMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseNumberMap, &v.DenseNumberMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseSetMap:
			return deserializeDenseSetMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseSetMap, &v.DenseSetMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseStringMap:
			return deserializeDenseStringMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseStringMap, &v.DenseStringMap)
			case schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseStructMap:
			return deserializeDenseStructMap(d, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput_denseStructMap, &v.DenseStructMap)
		}
		return nil
	})
}
func (c *Client) addOperationRpcV2CborDenseMapsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.RpcV2CborDenseMaps, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.RpcV2CborDenseMaps, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsInput, schemas.SmithyGoSynthetic_RpcV2CborDenseMapsOutput), output: &RpcV2CborDenseMapsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "RpcV2CborDenseMaps"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addUserAgentFeatureProtocolRPCV2CBOR(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opRpcV2CborDenseMaps(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opRpcV2CborDenseMaps(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "RpcV2CborDenseMaps",
	}
}
