// Code generated by smithy-go-codegen DO NOT EDIT.


package smithyrpcv2cbor

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/smithyrpcv2cbor/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
)

func (c *Client) OptionalInputOutput(ctx context.Context, params *OptionalInputOutputInput, optFns ...func(*Options)) (*OptionalInputOutputOutput, error) {
	if params == nil { params = &OptionalInputOutputInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "OptionalInputOutput", params, optFns, c.addOperationOptionalInputOutputMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*OptionalInputOutputOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type OptionalInputOutputInput struct {
	
	Value *string
	
	noSmithyDocumentSerde
}

func (v *OptionalInputOutputInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OptionalInputOutputInput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_OptionalInputOutputInput_value, v.Value)
	s.CloseMap()
}
func (v *OptionalInputOutputInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OptionalInputOutputInput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_OptionalInputOutputInput_value:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_OptionalInputOutputInput_value, &v.Value)
		}
		return nil
	})
}
type OptionalInputOutputOutput struct {
	
	Value *string
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *OptionalInputOutputOutput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OptionalInputOutputOutput)
	s.WriteStringPtr(schemas.SmithyGoSynthetic_OptionalInputOutputOutput_value, v.Value)
	s.CloseMap()
}
func (v *OptionalInputOutputOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OptionalInputOutputOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_OptionalInputOutputOutput_value:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_OptionalInputOutputOutput_value, &v.Value)
		}
		return nil
	})
}
func (c *Client) addOperationOptionalInputOutputMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OptionalInputOutput, schemas.SmithyGoSynthetic_OptionalInputOutputInput, schemas.SmithyGoSynthetic_OptionalInputOutputOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OptionalInputOutput, schemas.SmithyGoSynthetic_OptionalInputOutputInput, schemas.SmithyGoSynthetic_OptionalInputOutputOutput), output: &OptionalInputOutputOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "OptionalInputOutput"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addUserAgentFeatureProtocolRPCV2CBOR(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opOptionalInputOutput(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opOptionalInputOutput(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "OptionalInputOutput",
	}
}
