// Code generated by smithy-go-codegen DO NOT EDIT.


package jsonrpc10

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc10/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc10/types"
)

func (c *Client) OperationWithRequiredMembersWithDefaults(ctx context.Context, params *OperationWithRequiredMembersWithDefaultsInput, optFns ...func(*Options)) (*OperationWithRequiredMembersWithDefaultsOutput, error) {
	if params == nil { params = &OperationWithRequiredMembersWithDefaultsInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "OperationWithRequiredMembersWithDefaults", params, optFns, c.addOperationOperationWithRequiredMembersWithDefaultsMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*OperationWithRequiredMembersWithDefaultsOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type OperationWithRequiredMembersWithDefaultsInput struct {
	
	noSmithyDocumentSerde
}

func (v *OperationWithRequiredMembersWithDefaultsInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsInput)
	s.CloseMap()
}
func (v *OperationWithRequiredMembersWithDefaultsInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsInput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
type OperationWithRequiredMembersWithDefaultsOutput struct {
	
	// This member is required.
	RequiredBlob []byte
	
	// This member is required.
	RequiredBoolean *bool
	
	// This member is required.
	RequiredByte *int8
	
	// This member is required.
	RequiredDouble *float64
	
	// This member is required.
	RequiredEnum types.RequiredEnum
	
	// This member is required.
	RequiredFloat *float32
	
	// This member is required.
	RequiredIntEnum types.RequiredIntEnum
	
	// This member is required.
	RequiredInteger *int32
	
	// This member is required.
	RequiredList []string
	
	// This member is required.
	RequiredLong *int64
	
	// This member is required.
	RequiredMap map[string]string
	
	// This member is required.
	RequiredShort *int16
	
	// This member is required.
	RequiredString *string
	
	// This member is required.
	RequiredTimestamp *time.Time
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *OperationWithRequiredMembersWithDefaultsOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredBlob:
			return d.ReadBlob(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredBlob, &v.RequiredBlob)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredBoolean:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredBoolean, &v.RequiredBoolean)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredByte:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredByte, &v.RequiredByte)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredDouble:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredDouble, &v.RequiredDouble)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredEnum:
			var ev string
			if err := d.ReadString(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredEnum, &ev); err != nil {
			    return err
			}
			v.RequiredEnum = types.RequiredEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredFloat:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredFloat, &v.RequiredFloat)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredIntEnum:
			var ev int32
			if err := d.ReadInt32(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredIntEnum, &ev); err != nil {
			    return err
			}
			v.RequiredIntEnum = types.RequiredIntEnum(ev)
			return nil
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredInteger:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredInteger, &v.RequiredInteger)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredList:
			return deserializeRequiredStringList(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredList, &v.RequiredList)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredLong:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredLong, &v.RequiredLong)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredMap:
			return deserializeRequiredStringMap(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredMap, &v.RequiredMap)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredShort:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredShort, &v.RequiredShort)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredString:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredString, &v.RequiredString)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredTimestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput_requiredTimestamp, &v.RequiredTimestamp)
		}
		return nil
	})
}
func (c *Client) addOperationOperationWithRequiredMembersWithDefaultsMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OperationWithRequiredMembersWithDefaults, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsInput, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OperationWithRequiredMembersWithDefaults, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsInput, schemas.SmithyGoSynthetic_OperationWithRequiredMembersWithDefaultsOutput), output: &OperationWithRequiredMembersWithDefaultsOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "OperationWithRequiredMembersWithDefaults"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opOperationWithRequiredMembersWithDefaults(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opOperationWithRequiredMembersWithDefaults(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "OperationWithRequiredMembersWithDefaults",
	}
}
