// Code generated by smithy-go-codegen DO NOT EDIT.


package jsonrpc10

import (
	awsmiddleware "github.com/aws/aws-sdk-go-v2/aws/middleware"
	"context"
	"fmt"
	"github.com/aws/smithy-go/middleware"
	"github.com/aws/aws-sdk-go-v2/internal/protocoltest/jsonrpc10/schemas"
	smithy "github.com/aws/smithy-go"
	smithyhttp "github.com/aws/smithy-go/transport/http"
	"time"
)

func (c *Client) OperationWithRequiredMembers(ctx context.Context, params *OperationWithRequiredMembersInput, optFns ...func(*Options)) (*OperationWithRequiredMembersOutput, error) {
	if params == nil { params = &OperationWithRequiredMembersInput{} }
	
	result, metadata, err := c.invokeOperation(ctx, "OperationWithRequiredMembers", params, optFns, c.addOperationOperationWithRequiredMembersMiddlewares)
	if err != nil { return nil, err }
	
	out := result.(*OperationWithRequiredMembersOutput)
	out.ResultMetadata = metadata
	return out, nil
}

type OperationWithRequiredMembersInput struct {
	
	noSmithyDocumentSerde
}

func (v *OperationWithRequiredMembersInput) Serialize(s smithy.ShapeSerializer) {
	s.WriteMap(schemas.SmithyGoSynthetic_OperationWithRequiredMembersInput)
	s.CloseMap()
}
func (v *OperationWithRequiredMembersInput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersInput, func(s *smithy.Schema) error {
		switch s {
		}
		return nil
	})
}
type OperationWithRequiredMembersOutput struct {
	
	// This member is required.
	RequiredBlob []byte
	
	// This member is required.
	RequiredBoolean *bool
	
	// This member is required.
	RequiredByte *int8
	
	// This member is required.
	RequiredDouble *float64
	
	// This member is required.
	RequiredFloat *float32
	
	// This member is required.
	RequiredInteger *int32
	
	// This member is required.
	RequiredList []string
	
	// This member is required.
	RequiredLong *int64
	
	// This member is required.
	RequiredMap map[string]string
	
	// This member is required.
	RequiredShort *int16
	
	// This member is required.
	RequiredString *string
	
	// This member is required.
	RequiredTimestamp *time.Time
	
	// Metadata pertaining to the operation's result.
	ResultMetadata middleware.Metadata
	
	noSmithyDocumentSerde
}

func (v *OperationWithRequiredMembersOutput) Deserialize(d smithy.ShapeDeserializer) error {
	return smithy.ReadStruct(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput, func(s *smithy.Schema) error {
		switch s {
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredBlob:
			return d.ReadBlob(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredBlob, &v.RequiredBlob)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredBoolean:
			return d.ReadBoolPtr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredBoolean, &v.RequiredBoolean)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredByte:
			return d.ReadInt8Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredByte, &v.RequiredByte)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredDouble:
			return d.ReadFloat64Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredDouble, &v.RequiredDouble)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredFloat:
			return d.ReadFloat32Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredFloat, &v.RequiredFloat)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredInteger:
			return d.ReadInt32Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredInteger, &v.RequiredInteger)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredList:
			return deserializeRequiredStringList(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredList, &v.RequiredList)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredLong:
			return d.ReadInt64Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredLong, &v.RequiredLong)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredMap:
			return deserializeRequiredStringMap(d, schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredMap, &v.RequiredMap)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredShort:
			return d.ReadInt16Ptr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredShort, &v.RequiredShort)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredString:
			return d.ReadStringPtr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredString, &v.RequiredString)
			case schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredTimestamp:
			return d.ReadTimePtr(schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput_requiredTimestamp, &v.RequiredTimestamp)
		}
		return nil
	})
}
func (c *Client) addOperationOperationWithRequiredMembersMiddlewares(stack *middleware.Stack, options Options) (err error) {
	if err := stack.Serialize.Add(&setOperationInputMiddleware{}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Serialize.Add(&serializeRequestMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OperationWithRequiredMembers, schemas.SmithyGoSynthetic_OperationWithRequiredMembersInput, schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput)}, middleware.After); err != nil {
	    return err
	}
	if err := stack.Deserialize.Add(&deserializeResponseMiddleware{options: &options, operationSchema: smithy.NewOperationSchema(schemas.OperationWithRequiredMembers, schemas.SmithyGoSynthetic_OperationWithRequiredMembersInput, schemas.SmithyGoSynthetic_OperationWithRequiredMembersOutput), output: &OperationWithRequiredMembersOutput{}}, middleware.After); err != nil {
	    return err
	}
	if err := addProtocolFinalizerMiddlewares(stack, options, "OperationWithRequiredMembers"); err != nil {
	    return fmt.Errorf("add protocol finalizers: %v", err)
	}
	
	if err = addlegacyEndpointContextSetter(stack, options); err != nil {
	return err
	}
	if err = addSetLoggerMiddleware(stack, options); err != nil {
	return err
	}
	if err = addClientRequestID(stack); err != nil {
	return err
	}
	if err = addComputeContentLength(stack); err != nil {
	return err
	}
	if err = addResolveEndpointMiddleware(stack, options); err != nil {
	return err
	}
	if err = addComputePayloadSHA256(stack); err != nil {
	return err
	}
	if err = addRetry(stack, options); err != nil {
	return err
	}
	if err = addRawResponseToMetadata(stack); err != nil {
	return err
	}
	if err = addRecordResponseTiming(stack); err != nil {
	return err
	}
	if err = addSpanRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addClientUserAgent(stack, options); err != nil {
	return err
	}
	if err = smithyhttp.AddErrorCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = smithyhttp.AddCloseResponseBodyMiddleware(stack); err != nil {
	return err
	}
	if err = addSetLegacyContextSigningOptionsMiddleware(stack); err != nil {
	return err
	}
	if err = addTimeOffsetBuild(stack, c); err != nil {
	return err
	}
	if err = addUserAgentRetryMode(stack, options); err != nil {
	return err
	}
	if err = addCredentialSource(stack, options); err != nil {
	return err
	}
	if err = stack.Initialize.Add(newServiceMetadataMiddleware_opOperationWithRequiredMembers(options.Region, ), middleware.Before); err != nil {
	return err
	}
	if err = addRecursionDetection(stack); err != nil {
	return err
	}
	if err = addRequestIDRetrieverMiddleware(stack); err != nil {
	return err
	}
	if err = addResponseErrorMiddleware(stack); err != nil {
	return err
	}
	if err = addRequestResponseLogging(stack, options); err != nil {
	return err
	}
	if err = addDisableHTTPSMiddleware(stack, options); err != nil {
	return err
	}
	if err = addInterceptBeforeRetryLoop(stack, options); err != nil {
	return err
	}
	if err = addInterceptAttempt(stack, options); err != nil {
	return err
	}
	if err = addInterceptors(stack, options); err != nil {
	return err
	}
	return nil
}

func newServiceMetadataMiddleware_opOperationWithRequiredMembers(region string) *awsmiddleware.RegisterServiceMetadata {
	 return &awsmiddleware.RegisterServiceMetadata{
	Region: region,
	ServiceID: ServiceID,
	OperationName: "OperationWithRequiredMembers",
	}
}
